<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="content/images/ejmeri-1.ico" type="image/x-icon" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PET.FÁCIL</title>

    <!-- Bootstrap Core CSS -->
    <link href="content/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="content/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="content/magnific-popup/magnific-popup.css?<?php echo date('l jS \of F Y h:i:s A'); ?>" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="content/css/creative.min.css?<?php echo date('l jS \of F Y h:i:s A'); ?>" rel="stylesheet"> 

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Pet.fácil</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">Porque adotar ?</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Serviços</a>
                    </li> 
                    <li>
                        <a class="page-scroll" href="#portfolio">Histórias</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contatos</a>
                    </li>
					 <li>
                        <a class="page-scroll" href="login">Quero adotar</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                
                <div class="image-banner">
                    <img src="content/images/ejmeri-1.png"  style="width: 30%; margin: 0 auto;"class="img-responsive" alt="">
                </div>
                <!--<h1 id="homeHeading"><strong>PET.FÁCIL</strong></h1>-->
                 <hr>
                <!--<p>Uma plataforma livre, que busca auxiliar o processo de adoção e doação de animais.</p> -->
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Veja mais</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Encontre aqui a felicidade para seu lar!</h2>
                    <hr class="light">
                    <p class="">Você sabia que há mais de 30 milhões de cães e gatos abandonados ? Você pode mudar isso! Basta entrar em nossa plataforma e adotar ou doar um novo amiginho. </p>
                    <a href="#services" class="page-scroll btn btn-default btn-xl sr-button">Começar!</a>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Pets <i class="fa fa-heart" style="color:red;"> </i> <i class="fa fa-paw fa-1x"></i></h2>
                    <hr class="">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
				<div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="login" style="color: black;" alt="Faça seu cadastro"><i class="fa fa-4x fa-sign-in sr-icons"></i></a>
                        <a href="login" style="color: black;"><h3>Quero participar</h3></a>
                        <p class="text-muted">Faça seu cadastro e comece a adotar ou doar um animal.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-thumbs-o-up sr-icons" style="color:blue;"></i>
                        <h3>ONG's</h3>
                        <p class="text-muted">Algumas parcerias que nós temos.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-bath sr-icons"></i>
                        <h3>Você confia em como seu pet é tratado ?</h3>
                        <p class="text-muted">Veja aqui alguns pet shop com serviços de qualidade.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i id="heart" class="fa fa-4x fa-heart-o sr-icons" style="color:red;"></i>
                        <h3>Um pet é como um filho</h3>
                        <p class="text-muted">É muito importante ter um animal de estimação em sua vida.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="no-padding" id="portfolio">
	    <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Histórias que deram certo <i class="fa fa-handshake-o fa-1x">  </i> <i class="fa fa-paw fa-1x"></i> </h2>
                    <hr class="">
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row no-gutter popup-gallery">
                <div class="col-lg-4 col-sm-6">
                    <a href="content/images/1.jpg" class="portfolio-box">
                        <img src="content/images/1.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="content/images/2.jpg" class="portfolio-box">
                        <img src="content/images/2.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="content/images/3.jpg" class="portfolio-box">
                        <img src="content/images/3.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="content/images/4.jpg" class="portfolio-box">
                        <img src="content/images/4.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="img/portfolio/fullsize/5.jpg" class="portfolio-box">
                        <img src="content/images/5.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="content/images/6.jpg" class="portfolio-box">
                        <img src="content/images/6.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!--<aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>Free Download at Start Bootstrap!</h2>
                <a href="http://startbootstrap.com/template-overviews/creative/" class="btn btn-default btn-xl sr-button">Download Now!</a>
            </div>
        </div>
    </aside>-->

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Quer falar conosco ?</h2>
                    <hr class="primary">
                    <p>Entre em contato</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>(11) 91234-4321</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:your-email@your-domain.com">feedback@petfacil.com.br</a></p>
                </div>
            </div>
        </div>
        
    </section>

    <!-- jQuery -->
    <script src="content/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="content/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="content/scrollreveal/scrollreveal.min.js"></script>
    <script src="content/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="content/js/creative.min.js?<?php echo 'Elmeri Moreno' ?>"></script>

</body>

</html>
