<!DOCTYPE html>

<?php error_reporting(!E_NOTICE); ?>
<html>
<head>
    <link rel="shortcut icon" href="content/images/ejmeri-1.ico" type="image/x-icon" />
	<title><?php echo $this->title; ?></title>
    <base href="<?php echo APP_ROOT;?>/">
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
    <meta name="keywords" content="<?php echo $this->keywords ?>">
    <meta name="author" content="<?php echo $this->autor ?>">
	<link href="content/site/css/style.css" rel="stylesheet" />
	<link href="content/site/css/master.css?<?php echo NEW_FILE ?>" rel="stylesheet" />
	<link href="content/site/css/petdetail.css?elmeri" rel="stylesheet" />
	<link href="content/site/css/pets.css?elmeri" rel="stylesheet">
	<link href="content/site/css/newlogin.css?elmeri" rel="stylesheet">
	<!-- Plugin CSS -->
    
    <!-- Plugin CSS -->
    <link href="content/magnific-popup/magnific-popup.css" rel="stylesheet">



	<!-- Custom Fonts -->
	<link href="content/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
</head>
<body>


<!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#top">Patinha Fácil</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-default" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Adotar um pet</a>
                    <ul class="dropdown-menu">
                        <?php if (count($view_estadospet) > 0) { ?>
                            <?php foreach ($view_estadospet as $li => $a){ ?>
                                <li>
                                    <a href="pets/index/<?php echo $a['Sigla'] ?>">  <?php echo $a['Nome'] ?>
                                    <span class="badge"> <?php echo $a['Quantidade'] ?></span> </a>
                                   
                                </li>
                             <?php 
                            }
                        }
                        else {
                            ?>  
                            <li>
                                <a href="javascript:;">Ainda não temos pets para doação <i class="fa fa-frown-o"></i></a>
                            </li>
                        <?php }
                        
                        ?>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Achados e perdidos</a>
                    <ul class="dropdown-menu">
                        <?php if (count($view_achadosperdidos) > 0) { ?>
                            <?php foreach ($view_achadosperdidos as $li => $a){ ?>
                                <li>
                                    <a href="ajuda/achadoseperdidos/<?php echo $a['Sigla'] ?>">  <?php echo $a['Nome'] ?>
                                    <span class="badge"> <?php echo $a['Quantidade'] ?></span> </a>
                                   
                                </li>
                             <?php 
                            }
                        }
                        else {
                            ?>  
                            <li>
                                <a href="javascript:;">Ainda não temos pets nessa área</a>
                            </li>
                        <?php }
                        
                        ?>
                    </ul>
                </li>
                <li>
                    <a href="pets/novo" class="page-scroll">Ajudar um animal</a>
                </li>
                <li>
                    <a href="#services" class="page-scroll">Nossas opcões</a>
                </li>
                <li>
                    <a href="#portfolio" class="page-scroll">Pets disponíveis</a>
                </li>
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">Parceiros <i class="fa fa-hand-o-down" aria-hidden="true"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:;">Quero ser parceiro</a></li>
                        </ul>
                </li>
                <!-- <li>
                    <a href="#footer" class="page-scroll">Sobre nós</a>
                </li> -->
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <!-- <li>
                        <a class="page-scroll" target="_blank" style="color:red; font-weight: bold" href="https://www.vakinha.com.br/vaquinha/ajude-a-pet-facil-870fcf77-9ea4-4381-8071-cebbc63ba436">Nos ajude</a>
                    </li> -->
                    <li>
                    <div class="dropdown" id="menu_notify">
                        <a id="dLabel" class="header-notify" role="button" data-toggle="dropdown" data-target="#" href="#">
                            Notificações <i class="fa fa-bell" <?php if(count($view_end) == 0) { ?> style="color:red" <?php }  else { ?> style="color:black" <?php } ?> aria-hidden="true"></i>
                        </a>
                        <ul class="dropdown-menu notifications" role="menu" aria-labelledby="dLabel">
 
                            <div class="notification-heading"><h4 class="menu-title">Notificações</h4>
                            <!-- <h4 class="menu-title pull-right">View all<i class="glyphicon glyphicon-circle-arrow-right"></i></h4> -->
                            </div>
                            <li class="divider"></li>
                        <div class="notifications-wrapper">
                             <?php if(count($view_end) == 0) { ?>
                                <a class="content" href="pessoa#endereco">
                                    <div class="notification-item">
                                        <h4 class="item-title">Endereço</h4>
                                        <p class="item-info">Olá, tudo bem? Não esqueça de atualizar seu endereço.</p>
                                    </div>
                                </a>
                            <?php  }
                            else { ?>
                                <a href="javascript:;" class="content">
                                    <div class="notification-item">
                                        <h4 class="item-title">Não há notificações</h4>
                                    </div>
                                </a>
                            <?php } ?>
                        </div>
                            <li class="divider"></li>
                            <!-- <div class="notification-footer"><h4 class="menu-title">View all<i class="glyphicon glyphicon-circle-arrow-right"></i></h4></div> -->
                        </ul>
                        
                        </div>
                    </li>
                     <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">Minha conta <i class="fa fa-hand-o-down" aria-hidden="true"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="pessoa" class="page-scroll">Perfil <i class="fa fa-user-circle-o" aria-hidden="true"></i></a></li>
                            <li><a href="login/Close" class="page-scroll">Sair <i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
                        </ul>
                    </li>
                    <!--<li class="dropdown">
                        <a href="#" class="dropdowntoggle" data-toggle="dropdown">Minha conta <i class="fa fa-hand-o-down" aria-hidden="true"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="pessoa" class="page-scroll">Meu Perfil</a></li>
                            <li class="divider"></li>
                            <li><a href="login/Close" class="page-scroll">Sair</a></li>                  
                        </ul>
                    </li>-->
                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

<!-- END NAVIGATION -->


<header class="header-home" id="top">
    <div class="text-vertical-center">
        <h1>Patinha Fácil</h1>
        <h3>Encontre aqui a felicidade para seu lar</h3>
        <br>
        <!--<a href="home#start" class="btn btn-black btn-lg">Começar</a>-->
    </div>
</header>



        <?php $this->Render(); ?>  <!-- RENDERIZAÇÃO DA PÁGINA-->
</section>
<!-- Footer -->
    <footer id="footer">
        <div class="container-in">
                <div class="col-10 text-center">
                    <h4><strong>Patinha Fácil</strong>
                    </h4>
                    <p>Barueri, São Paulo</p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> (11) 90000-0000</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i> <a class="facebook" href="mailto:contato@patinhafacil.com.br">contato@patinhafacil.com.br</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="https://www.facebook.com/patinhafacil" target="_blank" title="Visite nosso facebook"><i class="fa fa-facebook fa-fw fa-3x facebook"></i></a>
                        </li>
                        <li>
                            <a href="https://www.vakinha.com.br/vaquinha/ajude-a-pet-facil-870fcf77-9ea4-4381-8071-cebbc63ba436" target="_blank"><i class="fa fa-money fa-fw fa-3x money"></i></a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/patinhafacil"  target="_blank"><i class="fa fa-instagram fa-fw fa-3x instagram"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                <p class="text-muted">Copyright &copy; Pet Fácil <?php echo date("Y"); ?></p>
                </div>
        </div>
        <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
    </footer>

<!-- END Footer -->


</body>
</html>

<!-- jQuery -->
<script src="content/js/jquery.js"></script>
<!--<script src="content/jquery/jquery.min.js"></script>-->
<script src="content/js/bootstrap.min.js"></script>

<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script src="content/js/jquerytransateValidatorsToBR.js"></script>
<script src="content/js/global.js"></script>
<script src="content/js/jquery.mask.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<script src="content/scrollreveal/scrollreveal.min.js"></script>
<script src="content/magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="content/js/creative.min.js?<?php echo NEW_FILE;?>"></script>