<html>
<head>
	<link rel="shortcut icon" href="content/images/ejmeri-1.ico" type="image/x-icon" />
    <title><?php echo $this->title;?></title>
    <base href="<?php echo APP_ROOT;?>/">
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
    <meta name="keywords" content="<?php echo $this->keywords ?>">
    <meta name="author" content="<?php echo $this->autor ?>">
	<!--<link href="content/site/css/style.css" rel="stylesheet" />-->
	<link href="content/site/css/master.css?<?php echo NEW_FILE;?>" rel="stylesheet" />
    <link href="content/site/css/site.css?<?php echo NEW_FILE;?>" rel="stylesheet" />
	<!--<link href="content/site/css/petdetail.css" rel="stylesheet" />
	<link href="content/site/css/pets.css" rel="stylesheet">-->
    <link href="content/site/css/confirmadopt.css?<?php echo NEW_FILE;?>" rel="stylesheet">
	<link href="content/site/css/newlogin.css?<?php echo NEW_FILE;?>" rel="stylesheet">
    <link href="content/site/css/people.css?<?php echo NEW_FILE;?>" rel="stylesheet">
    <link href="content/upload/css/component.css?<?php echo NEW_FILE;?>" rel="stylesheet">
    <script src="content/site/js/site.js?<?php echo NEW_FILE;?>"></script>
    <link href="content/magnific-popup/magnific-popup.css?<?php echo NEW_FILE;?>" rel="stylesheet">


    <script src="content/js/jquery.js?<?php echo NEW_FILE;?>"></script>
	<link href="content/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script> -->
</head>
<body>


<!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default ">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="home">Patinha Fácil</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-default" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Adotar um pet</a>
                    <ul class="dropdown-menu">
                        <?php if (count($view_estadospet) > 0) { ?>
                            <?php foreach ($view_estadospet as $li => $a){ ?>
                                <li>
                                    <a href="pets/index/<?php echo $a['Sigla'] ?>">  <?php echo $a['Nome'] ?>
                                    <span class="badge"> <?php echo $a['Quantidade'] ?></span> </a>
                                   
                                </li>
                            <?php 
                            }
                        }
                        else {
                            ?>  
                            <li>
                                <a href="javascript:;">Ainda não temos pets para doação <i class="fa fa-frown-o"></i></a>
                            </li>
                        <?php }
                        
                        ?>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Achados e perdidos</a>
                    <ul class="dropdown-menu">
                        <?php if (count($view_achadosperdidos) > 0) { ?>
                            <?php foreach ($view_achadosperdidos as $li => $a){ ?>
                                <li>
                                    <a href="ajuda/achadoseperdidos/<?php echo $a['Sigla'] ?>">  <?php echo $a['Nome'] ?>
                                    <span class="badge"> <?php echo $a['Quantidade'] ?></span> </a>
                                   
                                </li>
                             <?php 
                            }
                        }
                        else {
                            ?>  
                            <li>
                                <a href="javascript:;">Ainda não temos pets nessa área</a>
                            </li>
                        <?php }
                        
                        ?>
                    </ul>
                </li>
                <li>
                    <a href="pets/novo" class="page-scroll">Ajudar um animal</a>
                </li>
                <li>
                    <a href="home#portfolio" class="page-scroll">Pets disponíveis</a>
                </li>
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">Parceiros <i class="fa fa-hand-o-down" aria-hidden="true"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Quero ser parceiro</a></li>
                        </ul>
                </li>
                <li>
                    <a href="#footer" class="page-scroll">Sobre nós</a>
                </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <!-- <li>
                        <a class="page-scroll" target="_blank" style="color:red; font-weight: bold" href="https://www.vakinha.com.br/vaquinha/ajude-a-pet-facil-870fcf77-9ea4-4381-8071-cebbc63ba436">Nos ajude</a>
                    </li> -->
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">Minha conta <i class="fa fa-hand-o-down" aria-hidden="true"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="pessoa" class="page-scroll">Perfil <i class="fa fa-user-circle-o" aria-hidden="true"></i></a></li>
                            <li><a href="login/Close" class="page-scroll">Sair <i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
                        </ul>
                    </li>
                    <!--<li class="dropdown">
                        <a href="#" class="dropdowntoggle" data-toggle="dropdown">Minha conta <i class="fa fa-hand-o-down" aria-hidden="true"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="pessoa" class="page-scroll">Meu Perfil</a></li>
                            <li class="divider"></li>
                            <li><a href="login/Close" class="page-scroll">Sair</a></li>                  
                        </ul>
                    </li>-->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

<!-- END NAVIGATION -->


<header class="header" id="top">
    <div class="text-vertical-center">
        <a href="home" class="link-black">
            <div class="banner">
                <div class="image-banner">
                    <img src="content/images/ejmeri-1.png"  style="margin: 0 auto;"class="img-responsive" alt="">                    
                </div>
            </div>
        </a>
        <h3 style="color: #5aa1d8">Patinha Fácil</h3>
        <h3 style="color: #FFF">Encontre aqui a felicidade para seu lar</h3>
        <!-- <a href="#start" class="btn btn-black btn-lg">Começar</a> -->
        <br>
        <!--<a href="#about" class="btn btn-dark btn-lg">Começar</a>-->
    </div>
</header>

<section id="start">
        <?php $this->Render(); ?>  <!-- RENDERIZAÇÃO DA PÁGINA-->
</section>



<!-- Footer -->
    <footer id="footer">
        <div class="container-in">
                <div class="col-10 text-center">
                    <h3><strong>Patinha Fácil</strong></h3>
                    <p>Barueri, São Paulo</p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> (11) 90000-0000</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i> <a class="facebook" href="mailto:contato@patinhafacil.com.br">contato@patinhafacil.com.br</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="https://www.facebook.com/patinhafacil" target="_blank" title="Visite nosso facebook"><i class="fa fa-facebook fa-fw fa-3x facebook"></i></a>
                        </li>
                        <li>
                            <a href="https://www.vakinha.com.br/vaquinha/ajude-a-pet-facil-870fcf77-9ea4-4381-8071-cebbc63ba436" target="_blank"><i class="fa fa-money fa-fw fa-3x money"></i></a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/patinhafacil" target="_blank"><i class="fa fa-instagram fa-fw fa-3x instagram"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                <p class="text-muted" style="color: blue">Copyright &copy; Patinha Fácil <?php echo date("Y"); ?></p>
                </div>
        </div>
        <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
    </footer>

<!-- END Footer -->


</body>
</html>


<!-- jQuery -->
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script src="content/js/jquerytransateValidatorsToBR.js"></script>
    <script src="content/js/global.js?<?php echo NEW_FILE;?>"></script>
    <script src="content/js/jquery.mask.js?<?php echo NEW_FILE;?>"></script>
    

    <!-- Bootstrap Core JavaScript -->
    <script src="content/js/bootstrap.min.js?<?php echo NEW_FILE;?>"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="content/scrollreveal/scrollreveal.min.js"></script>
    <script src="content/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="content/js/creative.min.js?<?php echo NEW_FILE;?>"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>



    <!-- Custom Theme JavaScript -->
    <script>
    // Closes the sidebar menu
    $("#menu-close").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#],[data-toggle],[data-target],[data-slide])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    //#to-top button appears after scrolling
    var fixed = false;
    $(document).scroll(function() {
        if ($(this).scrollTop() > 250) {
            if (!fixed) {
                fixed = true;
                // $('#to-top').css({position:'fixed', display:'block'});
                $('#to-top').show("slow", function() {
                    $('#to-top').css({
                        position: 'fixed',
                        display: 'block'
                    });
                });
            }
        } else {
            if (fixed) {
                fixed = false;
                $('#to-top').hide("slow", function() {
                    $('#to-top').css({
                        display: 'none'
                    });
                });
            }
        }
    });
    // Disable Google Maps scrolling
    // See http://stackoverflow.com/a/25904582/1607849
    // Disable scroll zooming and bind back the click event
    var onMapMouseleaveHandler = function(event) {
        var that = $(this);
        that.on('click', onMapClickHandler);
        that.off('mouseleave', onMapMouseleaveHandler);
        that.find('iframe').css("pointer-events", "none");
    }
    var onMapClickHandler = function(event) {
            var that = $(this);
            // Disable the click handler until the user leaves the map area
            that.off('click', onMapClickHandler);
            // Enable scrolling zoom
            that.find('iframe').css("pointer-events", "auto");
            // Handle the mouse leave event
            that.on('mouseleave', onMapMouseleaveHandler);
        }
        // Enable map zooming with mouse scroll when the user clicks the map
    $('.map').on('click', onMapClickHandler);
    </script>

<!--JQUERY/JAVASCRIPT PAGE NEWPET-->

    <script type="text/javascript">
        $(document).ready(function(){
            var formulario =  $("#frmNovoPet");

            $('#frmNovoPet').validate({
                errorClass: 'text-errors',
                    
                    submitHandler: function (form) 
                    {
                        postForm(formulario,'txtretorno', 'result', 'teste');
                        $("#descricao").val('');
                        $("#nome").val('');
                        $("#peso").val('');
                        $("#dtnascimento").val('');
                        $('#image-holder').empty();
                    }
            })
        });

    </script>

<!--JQUERY/JAVASCRIPT PAGE NEWPET-->

            <!--JQUERY/JAVASCRIPT PAGE NEWLOGIN-->

<script type="text/javascript">
    $(document).ready(function(){

            var formulario =  $("#frmCadastro");
            var cpfcnpj = $('#CPF').val();

            $("#frmCadastro").validate({
                    errorClass: 'text-errors',
                    rules: {
                            PessoaCpfCnpj: {
                                digits: true
                            },
                            field: {
                                required: true
                                // minlength: 3
                            },
                            repassword: {
                                equalTo: "#password"
                            }
                    },
                    submitHandler: function (form) {
                        var login = document.getElementById("txtlogin").innerText;
                        
                        if(login.length > 0) {
                            $("#user").focus();
                            return;
                        }

                        postForm(formulario,'txtHint', 'result', 'login');
                        clearInputs();
                    }   
            });

                function clearInputs(){
                    $("#txtcpfcnpj").val('');
                    $("#CNPJ").val('');
                    $("#Rg").val('');
                    $("#Nome").val('');
                    $("#Apelido").val('');
                    $("#Email").val('');
                    $("#user").val('');
                    $("#password").val('');
                    $("#repassword").val('');
                    $("#Telefone").val('');
                }
    });
</script>
        <!--FIM JQUERY/JAVASCRIPT PAGE NEWLOGIN-->

<script type="text/javascript">
     
     var formulario =  $("#ConfirmarAdocao");

     $('#ConfirmarAdocao').validate({
         errorClass: 'text-errors',
            
            submitHandler: function (form) 
            {
                postForm(formulario,'txtretorno', 'result');
                $("#descricao").val('');
            }
    });

</script>