<html>
    <head>
        <link rel="shortcut icon" href="content/images/ejmeri-1.ico" type="image/x-icon" />
        <title><?php echo $this->title;?></title>
        <base href="<?php echo APP_ROOT;?>/">
        <meta name="author" content="<?php echo $this->autor ?>">
        <meta name="keywords" content="<?php echo $this->keywords ?>">
        <meta charset="utf-8">
         <!-- Bootstrap Core CSS -->
        <link href="content/bootstrap/css/bootstrap.min.css?v" rel="stylesheet">
        <link href="content/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="content/site/css/master.css?<?php echo NEW_FILE;?>" rel="stylesheet" media="all">
        <link href="content/site/css/login.css?elmeri" rel="stylesheet" media="all">
        <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
        <script src="content/site/js/site.js?<?php echo NEW_FILE;?>"></script>
        <link href="content/magnific-popup/magnific-popup.css?elmeri" rel="stylesheet">

    </head>
    <body>
        <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="">
            
            <div class="container-fluid">
                <div class="navbar-header">
                    <button class="navbar-toggle" data-target="#navbar-collapse" data-toggle="collapse" type="button">
                        <span class="sr-only">Toggle navigation</span> Login <i class="fa fa-bars"></i>
                    </button>
                    <div class="container-in text-center">
                        <a class="navbar-brand" href="<?php echo APP_ROOT ?>">Patinha Fácil</a>
                    </div>
                </div>
                <div class="collapse navbar-collapse" id="navbar-collapse">
                <div class="col-lg-10">
                    <div>
                    <form id="frmLogin" action="login/index/<?php echo $view_redirect ?>" class="padding"  method="POST">
                        <div class="col-lg-3 col-lg-offset-5">
                            <div class="input-group">
                                <span class="input-group-addon">
                                <i class="fa fa-user-circle-o"></i>
                                </span>
                                <input class="form-control" style="font-size:12px" id="txtlogin" name="UsuarioLogin" minLength=3 maxLength=30 placeholder="E-mail" type="text" required>                                                    
                            </div>
                        </div>                                      
                        <div class="col-lg-3">
                            <div class="input-group">
                                <span class="input-group-addon">
                                <i class="fa fa-key"></i>
                                </span>
                                <input class="form-control" style="font-size:12px"  id="txtsenha" name="UsuarioSenha" placeholder="Senha" type="password" required>
                            </div>
                            <div id="result" class="text-warning">
                                <span id="retorno"></span>
                            </div>
                            <div class="col-lg-12 row">
                                <a href="login/esqueciasenha" class="link-w">Esqueceu sua senha ?</a>                         
                            </div>
                        </div>
                        <div class="col-lg-1">
                            <button  type="submit" class="btn btn-blue" id="enter" name="enter">Entrar  <i class="fa fa-unlock-alt"></i></button>
                            <!--<input type="submit" formaction="login" name="adotar" class="btn fa fa-5x" title="Adote!" value ="&#xf004;">                          -->
                        </div>
                    </form>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    </div>
   <section>
        <?php $this->Render(); ?> <!-- RENDERIZAÇÃO DA PÁGINA -->       
   </section>    

        <!-- Footer -->
    <footer id="footer" style="background-color: #5aa1d8">
        <div class="container-in">
                <div class="col-10 text-center">
                    <h4><strong>Patinha Fácil</strong>
                    </h4>
                   <p>Barueri, São Paulo</p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> (11) 90000-0000</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:contato@patinhafacil.com.br"> contato@patinhafacil.com.br </a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="https://www.facebook.com/patinhafacil" target="_blank" title="Visite nosso facebook"><i class="fa fa-facebook fa-fw fa-3x facebook"></i></a>
                        </li>
                        <li>
                            <a href="https://www.vakinha.com.br/vaquinha/ajude-a-pet-facil-870fcf77-9ea4-4381-8071-cebbc63ba436" target="_blank"><i class="fa fa-money fa-fw fa-3x money"></i></a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/patinhafacil" target="_blank" title="Visite nosso instagram"><i class="fa fa-instagram fa-fw fa-3x instagram"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                <p class="text-muted">Copyright &copy; Patinha Fácil <?php echo date("Y"); ?></p>
                </div>
        </div>
        <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
    </footer>

<!-- END Footer -->
    </body>
</html>
    <!-- jQuery -->
    <script src="content/js/jquery.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script src="content/js/jquerytransateValidatorsToBR.js"></script>
    <script src="content/js/global.js?<?php echo NEW_FILE; ?>"></script>
    <script src="content/js/jquery.mask.js"></script>
    
    <!-- Bootstrap Core JavaScript -->
    <script src="content/js/bootstrap.min.js"></script>
    
    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="content/scrollreveal/scrollreveal.min.js"></script>
    <script src="content/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="content/js/creative.min.js?<?php echo NEW_FILE; ?>"></script>



   <script type="text/javascript">
   
     $(document).ready(function(){
            $("#result").hide();
            var formulario = $("#frmLogin");

                $("#frmLogin").validate({
                    errorClass: 'text-errors',
                    rules: {
                        fields: {
                            required: true
                        }
                    },
                        submitHandler: function (form) {
                            postFormLogin(formulario, 'retorno', 'result', 'home');
                        }
                });
     });
   </script>
                            <!--JQUERY/JAVASCRIPT PAGE NEWLOGIN-->

    <script type="text/javascript">
        $(document).ready(function(){

                var formulario =  $("#frmCadastro");
                

                $("#frmCadastro").validate({
                        errorClass: 'text-errors',
                        rules: {
                                PessoaCpfCnpj: {
                                    digits: true
                                },
                                field: {
                                    required: true
                                    // minlength: 3
                                },
                                repassword: {
                                    equalTo: "#password"
                                }
                        },
                        submitHandler: function (form) {
                            var login = document.getElementById("returnlogin").innerText;
                            // var cpfcnpj = $('#CPF').val();
                            
                            if(login.length > 0) {
                                $("#user").focus();
                                return;
                            }

                            postForm(formulario,'txtHint', 'result', '');
                            clearInputs();
                        }   
                });

                    function clearInputs(){
                        $("#txtcpfcnpj").val('');
                        $("#Rg").val('');
                        $("#Nome").val('');
                        $("#Apelido").val('');
                        $("#Email").val('');
                        $("#user").val('');
                        $("#password").val('');
                        $("#repassword").val('');
                        $("#Telefone").val('');
                    }



        $('#result').hide();

        $("#linkfisica").addClass("selected");
        
            $("#linkfisica").click(function(){

                $("#txtcpfcnpj").val('');

                $("#Apelido").attr("placeholder", "Apelido");
                $("#Nome").attr("placeholder", "Nome");
                $("#Rg").attr("placeholder", "RG");
                $("#txtcpfcnpj").attr("placeholder", "CPF");

                $("#linkfisica").addClass("selected");
                $("#linkjuridica").removeClass("selected");

                document.getElementById("txtCPF").innerHTML = "";
                
            });
        
            $("#linkjuridica").click(function(){
                $("#txtcpfcnpj").val('');

                // $("#txtcpfcnpj").attr("placeholder", "00.000.000/0000-00");
                $("#Apelido").attr("placeholder", "Nome Fantasia");
                $("#Nome").attr("placeholder", "Razão Social/Nome Fantasia");
                $("#txtcpfcnpj").attr("placeholder", "CNPJ");
                $("#Rg").attr("placeholder", "Inscrição Estadual");

                $("#linkjuridica").addClass("selected");
                $("#linkfisica").removeClass("selected");

                document.getElementById("txtCPF").innerHTML = "";
            });
        });
    </script>


                                    <!--FIM JQUERY/JAVASCRIPT PAGE NEWLOGIN-->


                                    <!--INICIO PERDI MINHA SENHA-->

<script type="text/javascript">
    $(document).ready(function(){

        var formulario =  $("#frmRecuperar");


        $("#frmRecuperar").validate({
                errorClass: 'text-errors',
                rules: {
                        field: {
                            required: true
                            // minlength: 3
                        }
                },
                submitHandler: function (form) {

                    postForm(formulario,'retornosenha', 'resultsenha', 'login');
                    clearInputs();
                }   
        });

        function clearInputs(){
            $("#user").val('');
        }
    });
</script>                 
                         <!--FIM PERDI MINHA SENHA-->


<script>
    $(document).ready(function(){
        $("#user").focusout(function () {
           showLogin($('#user').val());
        });
    });
</script>