<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="content/images/ejmeri-1.ico" type="image/x-icon" />
    <base href="<?php echo APP_ROOT;?>/">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Patinha Fácil</title>

    <!-- Bootstrap Core CSS -->
    <link href="content/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="content/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="content/magnific-popup/magnific-popup.css?v" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="content/css/creative.min.css?<?php echo NEW_FILE ?>" rel="stylesheet"> 

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" style="background-color: #f8f8f8">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" style="text-transform: capitalize;" href="#page-top">Patinha Fácil</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">Por que adotar ?</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#pets">Adotar um animal</a>
                    </li>
                    <li>
                        <a href="#achadoseperdidos" class="page-scroll">Achados e perdidos</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="login">Ajudar um animal</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Serviços</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contatos</a>
                    </li>
                    <li>
                        <a class="page-scroll" target="_blank" style="color:red" href="https://www.vakinha.com.br/vaquinha/ajude-a-pet-facil-870fcf77-9ea4-4381-8071-cebbc63ba436">Nos ajude</a>
                    </li>
                    <li>
                        <a href="login" class="page-scroll">Efetuar login <i class="fa fa-user-circle-o" aria-hidden="true"></i></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                
                <div class="image-banner">
                    <img src="content/images/ejmeri-1.png"  style="width: 30%; margin: 0 auto;"class="img-responsive" alt="">
                </div>
                <!--<h1 id="homeHeading"><strong>PET.FÁCIL</strong></h1>-->
                 <hr>
                <!--<p>Uma plataforma livre, que busca auxiliar o processo de adoção e doação de animais.</p> -->
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Veja mais</a>
            </div>
        </div>
    </header>

    <?php $this->Render(); ?>


<section id="contact" class="bg-primary">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Entre em contato</h2>
                <hr class="primary">
                <p>Opções de contato</p>
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-whatsapp fa-3x sr-contact" style="color: black"></i>
                <p>Ainda não temos</p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope fa-3x sr-contact" style="color: black"></i>
                <p><a href="mailto:contato@patinhafacil.com.br" style="color: white">contato@patinhafacil.com.br</a></p>
            </div>
        </div>
    </div>
        
</section>

    <!-- jQuery -->
    <script src="content/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="content/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="content/scrollreveal/scrollreveal.min.js"></script>
    <script src="content/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="content/js/creative.min.js?<?php echo 'ejmeri' ?>"></script>

</body>

</html> 
