<html>
<head>
    <link rel="shortcut icon" href="content/images/ejmeri-1.ico" type="image/x-icon" />
	<title><?php echo $this->title;?></title>
    <base href="<?php echo APP_ROOT;?>/">
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
    <meta name="keywords" content="<?php echo $this->keywords ?>">
    <meta name="author" content="<?php echo $this->autor ?>">
	<!--<link href="content/site/css/style.css" rel="stylesheet" />-->
	<link href="content/site/css/master.css?<?php echo NEW_FILE;?>" rel="stylesheet" />
    <link href="content/site/css/site.css?<?php echo NEW_FILE;?>" rel="stylesheet" />
	<!--<link href="content/site/css/petdetail.css" rel="stylesheet" />
	<link href="content/site/css/pets.css" rel="stylesheet">-->
    <link href="content/site/css/confirmadopt.css?<?php echo NEW_FILE;?>" rel="stylesheet">
	<link href="content/site/css/newlogin.css?<?php echo NEW_FILE;?>" rel="stylesheet">
    <link href="content/site/css/people.css?<?php echo NEW_FILE;?>" rel="stylesheet">
    <link href="content/upload/css/component.css?<?php echo NEW_FILE;?>" rel="stylesheet">
    <script src="content/site/js/site.js?<?php echo NEW_FILE;?>"></script>
    <link href="content/magnific-popup/magnific-popup.css?<?php echo NEW_FILE;?>" rel="stylesheet">

    <!-- jQuery -->
    <script src="content/js/jquery.js?<?php echo NEW_FILE;?>"></script>
    <script src="content/js/paginator.js"></script>
	<link href="content/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
</head>
<body>

<!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="">Pet.fácil</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-default" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Adotar um pet</a>
                    <ul class="dropdown-menu">
                        <?php if (count($view_estadospet) > 0) { ?>
                            <?php foreach ($view_estadospet as $li => $a){ ?>
                                <li>
                                    <a href="pets/index/<?php echo $a['Sigla'] ?>">  <?php echo $a['Nome'] ?>
                                    <span class="badge"> <?php echo $a['Quantidade'] ?></span> </a>
                                   
                                </li>
                             <?php 
                            }
                        }
                        else {
                            ?>  
                            <li>
                                <a href="javascript:;">Ainda não temos pets para doação <i class="fa fa-frown-o"></i></a>
                            </li>
                        <?php }
                        
                        ?>
                    </ul>
                </li>
                <li>
                    <a href="#services" class="page-scroll">Nossas opcões</a>
                </li>
                <li>
                    <a href="home#portfolio" class="page-scroll">Pets disponíveis</a>
                </li>
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">Parceiros <i class="fa fa-hand-o-down" aria-hidden="true"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Quero ser um parceiro</a></li>
                        </ul>
                </li>
                <li>
                    <a href="#footer" class="page-scroll">Sobre nós</a>
                </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" target="_blank" style="color:red; font-weight: bold" href="https://www.vakinha.com.br/vaquinha/ajude-a-pet-facil-870fcf77-9ea4-4381-8071-cebbc63ba436">Nos ajude</a>
                    </li>
                    <li>
                        <a href="login" class="page-scroll">Efetuar login <i class="fa fa-user-circle-o" aria-hidden="true"></i></a>
                    </li>
                    <li>
                        <a href="login" class="page-scroll">Quero doar um pet <i class="fa fa-user-circle-o" aria-hidden="true"></i></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

<!-- END NAVIGATION -->

<header class="header" id="top">
    <div class="text-vertical-center">
        <a href="home" class="link-black">
            <div class="banner">
                <div class="image-banner">
                    <img src="content/images/ejmeri-1.png"  style="margin: 0 auto;"class="img-responsive" alt="">                    
                </div>
            </div>
        </a>
        <h3>Encontre aqui a felicidade para seu lar</h3>
        <a href="#start" class="btn btn-black btn-lg">Começar</a>
        <br>
        <!--<a href="#about" class="btn btn-dark btn-lg">Começar</a>-->
    </div>
</header>

<section id="start">
        <?php $this->Render(); ?>  <!-- RENDERIZAÇÃO DA PÁGINA-->
</section>
<!-- Footer -->
    <footer id="footer">
        <div class="container-in">
                <div class="col-10 text-center">
                    <h4><strong>PET.FÁCIL</strong>
                    </h4>
                    <p>Rua Manaira, 00 - Jardim Mutinga
                        <br>Barueri, São Paulo</p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> (11) 90000-0000</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:name@example.com">name@example.com</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="https://www.facebook.com/adtfacil" target="_blank" title="Visite nosso facebook"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/pet.facil"><i class="fa fa-instagram fa-fw fa-3x"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                <p class="text-muted">Copyright &copy; Pet Fácil <?php echo date("Y"); ?></p>
                </div>
        </div>
        <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
    </footer>

<!-- END Footer -->


</body>
</html>

    <script src="content/js/paginator.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script src="content/js/jquerytransateValidatorsToBR.js"></script>
    <script src="content/js/global.js?elmei"></script>
    <script src="content/js/jquery.mask.js?<?php echo NEW_FILE;?>"></script>
    

    <!-- Bootstrap Core JavaScript -->
    <script src="content/js/bootstrap.min.js"></script>
    
    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="content/scrollreveal/scrollreveal.min.js"></script>
    <script src="content/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="content/js/creative.min.js?<?php echo NEW_FILE;?>"></script>

        <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>


    <script>
    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#],[data-toggle],[data-target],[data-slide])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    //#to-top button appears after scrolling
    var fixed = false;
    $(document).scroll(function() {
        if ($(this).scrollTop() > 250) {
            if (!fixed) {
                fixed = true;
                // $('#to-top').css({position:'fixed', display:'block'});
                $('#to-top').show("slow", function() {
                    $('#to-top').css({
                        position: 'fixed',
                        display: 'block'
                    });
                });
            }
        } else {
            if (fixed) {
                fixed = false;
                $('#to-top').hide("slow", function() {
                    $('#to-top').css({
                        display: 'none'
                    });
                });
            }
        }
    });
    </script>
                      
    
                                <!--JQUERY/JAVASCRIPT PAGE PETS-->     
    <script>
        $(document).ready(function(){

            var espid = $('#especie').val();
            var uf = $('#UfId').val();

                showPet(espid, uf);
            
            // $("#items-filter").hide();

            $("#filters").click(function(){
                if($("#items-filter").is(':visible')) {
                        $("#items-filter").hide();
                }
                else {
                    $("#items-filter").show();
                }   
            });
        });


        function showPet(esp, uf) {
                postPartialView('pets/ListaPet/' + uf, 'ListPet'); 
        }

        function showRaca(especie) {
                postPartialView('pets/ListaRaca/' + especie, 'raca');        
        }
        function showFilterRaca(especie) {
                postPartialView('pets/FilterListaRaca/' + especie, 'raca');        
        }
            
    </script>
                            <!-- FIM JQUERY/JAVASCRIPT PAGE PETS-->   


<script type="text/javascript">
     
     var formulario =  $("#ConfirmarAdocao");

     $('#ConfirmarAdocao').validate({
         errorClass: 'text-errors',
            
            submitHandler: function (form) 
            {
                ConfirmaAdocao('ConfirmarAdocao');
            }
    });

</script>
