<!DOCTYPE html>

<?php error_reporting(!E_NOTICE); ?>
<html>
<head>
    <link rel="shortcut icon" href="content/images/dog.ico" type="image/x-icon" />
	<title><?php echo $this->title; ?></title>
    <base href="<?php echo APP_ROOT;?>/">
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="keywords" content="<?php echo $this->keywords ?>">
    <meta name="author" content="<?php echo $this->autor ?>">
	<link href="content/site/css/style.css" rel="stylesheet" />
	<link href="content/site/css/master.css" rel="stylesheet" />
	<link href="content/site/css/petdetail.css" rel="stylesheet" />
	<link href="content/site/css/pets.css" rel="stylesheet">
	<link href="content/site/css/newlogin.css" rel="stylesheet">
	<!-- Plugin CSS -->
    
    <!-- Plugin CSS -->
    <link href="content/magnific-popup/magnific-popup.css" rel="stylesheet">



	<!-- Custom Fonts -->
	<link href="content/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
</head>
<body>


<!-- Navigation -->
<a id="menu-toggle" href="#" class="btn btn-gray btn-lg toggle"><i class="fa fa-bars"></i></a>
<nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
        <li class="sidebar-brand">
            <a href="home" onclick=$("#menu-close").click();>Pet Fácil</a>
        </li>
        <!--<li>
            <a href="home" onclick=$("#menu-close").click();>Home</a>
        </li>-->
        <li>
            <a href="pets" onclick=$("#menu-close").click();>Adotar um pet</a>
        </li>
         <li>
            <a href="pets/novo" onclick=$("#menu-close").click();>Doar um pet</a>
        </li>
        <li>
            <a href="#services" onclick=$("#menu-close").click();>Nossas opcões</a>
        </li>
        <li>
            <a href="home#portfolio" onclick=$("#menu-close").click();>Pets disponíveis</a>
        </li>
        <li>
            <a href="#footer" onclick=$("#menu-close").click();>Sobre nós</a>
        </li>
        <li>
            <a href="pessoa" onclick=$("#menu-close").click();>Meu Perfil</a>
        </li>
        <li>
            <a href="login/Close" onclick=$("#menu-close").click();>Sair</a>
        </li>
    </ul>
</nav>

<!-- END NAVIGATION -->


<header class="header-home" id="top">
    <div class="text-vertical-center">
        <h1>Pet Fácil</h1>
        <h3>Encontre aqui a felicidade para seu lar</h3>
        <br>
        <a href="#about" class="btn btn-dark btn-lg">Começar</a>
    </div>
</header>

<!-- About -->
<section id="about" class="about">
    <div class="container-in">
        <div class="text-center">
            <h2>Aqui está o seu amigo!</h2>
            <p class="lead">Pet Fácil.</p>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

<?php $this->Render(); ?>  <!-- RENDERIZAÇÃO DA PÁGINA-->

<!-- Footer -->
    <footer id="footer">
        <div class="container-in">
                <div class="col-10 text-center">
                    <h4><strong>Pet Fácil</strong>
                    </h4>
                    <p>Rua Manaira, 00 - Jardim Mutinga
                        <br>Barueri, São Paulo</p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> (11) 90000-0000</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:name@example.com">name@example.com</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="https://www.facebook.com/adtfacil" target="_blank" title="Visite nosso facebook"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dribbble fa-fw fa-3x"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                <p class="text-muted">Copyright &copy; Pet Fácil <?php echo date("Y"); ?></p>
                </div>
        </div>
        <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
    </footer>

<!-- END Footer -->


</body>
</html>



    <!-- jQuery -->
    <script src="content/js/jquery.js"></script>
    <!--<script src="content/jquery/jquery.min.js"></script>-->
    <script src="content/js/bootstrap.min.js"></script>
    
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script src="content/js/jquerytransateValidatorsToBR.js"></script>
    <script src="content/js/global.js"></script>
    <script src="content/js/jquery.mask.js"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="content/scrollreveal/scrollreveal.min.js"></script>
    <script src="content/magnific-popup/jquery.magnific-popup.min.js"></script>


    <!-- Bootstrap Core JavaScript -->
   

    <!-- Custom Theme JavaScript -->
    <script>
    // Closes the sidebar menu
    $("#menu-close").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#],[data-toggle],[data-target],[data-slide])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    //#to-top button appears after scrolling
    var fixed = false;
    $(document).scroll(function() {
        if ($(this).scrollTop() > 250) {
            if (!fixed) {
                fixed = true;
                // $('#to-top').css({position:'fixed', display:'block'});
                $('#to-top').show("slow", function() {
                    $('#to-top').css({
                        position: 'fixed',
                        display: 'block'
                    });
                });
            }
        } else {
            if (fixed) {
                fixed = false;
                $('#to-top').hide("slow", function() {
                    $('#to-top').css({
                        display: 'none'
                    });
                });
            }
        }
    });
    // Disable Google Maps scrolling
    // See http://stackoverflow.com/a/25904582/1607849
    // Disable scroll zooming and bind back the click event
    var onMapMouseleaveHandler = function(event) {
        var that = $(this);
        that.on('click', onMapClickHandler);
        that.off('mouseleave', onMapMouseleaveHandler);
        that.find('iframe').css("pointer-events", "none");
    }
    var onMapClickHandler = function(event) {
            var that = $(this);
            // Disable the click handler until the user leaves the map area
            that.off('click', onMapClickHandler);
            // Enable scrolling zoom
            that.find('iframe').css("pointer-events", "auto");
            // Handle the mouse leave event
            that.on('mouseleave', onMapMouseleaveHandler);
        }
        // Enable map zooming with mouse scroll when the user clicks the map
    $('.map').on('click', onMapClickHandler);
    </script>
