<html>
<head>
    <link rel="shortcut icon" href="content/images/adopt.ico" type="image/x-icon" />
	<title>Página não encontrada</title>
    <base href="<?php echo APP_ROOT;?>/">
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link href="content/site/css/master.css" rel="stylesheet" />
    <link href="content/site/css/site.css" rel="stylesheet" />
    <script src="content/site/js/site.js"></script>
</head>
<body>

<header class="header" id="top">
    <div class="text-vertical-center">
        <h1>PET.FÁCIL</h1>
        <h3>Encontre aqui a felicidade para seu lar</h3>
        <!--<a href="#start" class="btn btn-dark btn-lg">Começar</a>-->
        <a href="login" class="btn btn-dark btn-lg">Voltar</a>
        <br>
        <!--<a href="#about" class="btn btn-dark btn-lg">Começar</a>-->
    </div>
</header>
    <section id="iniciar">
        <div class="container-in">
            <article class="about text-center">
                <h1>Página não encontrada!</h1>
                <h2> <?php echo ERROR; ?></h2>
                <h2><a href="home" class="link-blue">Clique aqui para voltar</a></h2>
            </article>
        </div>
    </section>
<!-- Footer -->
    <footer id="footer">
        <div class="container-in">
                <div class="col-10 text-center">
                    <h4><strong>PET.FÁCIL</strong>
                    </h4>
                    <p>Rua Manaira, 00 - Jardim Mutinga
                        <br>Barueri, São Paulo</p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> (11) 90000-0000</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:name@example.com">name@example.com</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="https://www.facebook.com/adtfacil" target="_blank" title="Visite nosso facebook"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/pet.facil"><i class="fa fa-instagram fa-fw fa-3x"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                <p class="text-muted">Copyright &copy; Pet Fácil <?php echo date("Y"); ?></p>
                </div>
        </div>
        <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
    </footer>

<!-- END Footer -->


</body>
</html>
