<?php
    $title = "Página não encontrada";
?>
<!DOCTYPE html>
<html>
<head>
	<title><?php echo $title; ?></title>
    <base href="<?php echo APP_ROOT;?>/">
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link href="content/site/css/style.css" rel="stylesheet" />
	<link href="content/site/css/master.css" rel="stylesheet" />
	
	<!-- Custom Fonts -->
	<link href="content/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
</head>
<body>
    
<a id="menu-toggle" href="#" class="btn btn-gray btn-lg toggle"><i class="fa fa-bars"></i></a>
<nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
        <li class="sidebar-brand">
            <a href="#top" onclick=$("#menu-close").click();>Ajude Fácil</a>
        </li>
        <li>
            <a href="home" onclick=$("#menu-close").click();>Home</a>
        </li>
        <li>
            <a href="pets" onclick=$("#menu-close").click();>Pets</a>
        </li>
        <li>
            <a href="#services" onclick=$("#menu-close").click();>Nossas opcões</a>
        </li>
        <li>
            <a href="#portfolio" onclick=$("#menu-close").click();>Portfolio</a>
        </li>
        <li>
            <a href="#contact" onclick=$("#menu-close").click();>Contact</a>
        </li>
        <li>
            <a href="#footer" onclick=$("#menu-close").click();>Sobre nós</a>
        </li>
        <li>
            <a href="login" onclick=$("#menu-close").click();>Exit</a>
        </li>
    </ul>
</nav>
<header class="header" id="top">
    <div class="text-vertical-center">
        <h1>Adote Fácil</h1>
        <h3>Encontre aqui a felicidade para seu lar</h3>
        <a href="#iniciar" class="btn btn-dark btn-lg">Começar</a>
        <br>
        <!--<a href="#about" class="btn btn-dark btn-lg">Começar</a>-->
    </div>
</header>
    <section id="iniciar">
        <div class="container">
            <article class="about text-center">
                <h1>Página não encontrada!</h1>
                <h2> <?php echo ERROR; ?></h2>
                <h2><a href="home" class="link-blue">Clique aqui para voltar</a></h2>
            </article>
        </div>
    </section>

<!--<?php
    // include('Content/shared/masterfooter.php');
?>-->
    <!-- Footer -->
    <footer id="footer">
        <div class="container">
                <div class="col-10 text-center">
                    <h4><strong>Adote Fácil</strong>
                    </h4>
                    <p>Rua Manaira, 00 - Jardim Mutinga
                        <br>Barueri, São Paulo</p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> (11) 90000-0000</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:name@example.com">name@example.com</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="https://www.facebook.com/adtfacil" target="_blank" title="Visite nosso facebook"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dribbble fa-fw fa-3x"></i></a>
                        </li>
                    </ul>
                    <hr class="small">
                <p class="text-muted">Copyright &copy; Adote Fácil <?php echo date("Y"); ?></p>
                </div>
        </div>
        <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
    </footer>

<!-- END Footer -->
 </body>

</html>


   <!-- jQuery -->
    <script src="Content/js/jquery.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script src="content/js/jquerytransateValidatorsToBR.js"></script>
    <script src="content/js/global.js"></script>
    <script src="content/js/jquery.mask.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="Content/js/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script>
    // Closes the sidebar menu
    $("#menu-close").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#],[data-toggle],[data-target],[data-slide])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    //#to-top button appears after scrolling
    var fixed = false;
    $(document).scroll(function() {
        if ($(this).scrollTop() > 250) {
            if (!fixed) {
                fixed = true;
                // $('#to-top').css({position:'fixed', display:'block'});
                $('#to-top').show("slow", function() {
                    $('#to-top').css({
                        position: 'fixed',
                        display: 'block'
                    });
                });
            }
        } else {
            if (fixed) {
                fixed = false;
                $('#to-top').hide("slow", function() {
                    $('#to-top').css({
                        display: 'none'
                    });
                });
            }
        }
    });
    // Disable Google Maps scrolling
    // See http://stackoverflow.com/a/25904582/1607849
    // Disable scroll zooming and bind back the click event
    var onMapMouseleaveHandler = function(event) {
        var that = $(this);
        that.on('click', onMapClickHandler);
        that.off('mouseleave', onMapMouseleaveHandler);
        that.find('iframe').css("pointer-events", "none");
    }
    var onMapClickHandler = function(event) {
            var that = $(this);
            // Disable the click handler until the user leaves the map area
            that.off('click', onMapClickHandler);
            // Enable scrolling zoom
            that.find('iframe').css("pointer-events", "auto");
            // Handle the mouse leave event
            that.on('mouseleave', onMapMouseleaveHandler);
        }
        // Enable map zooming with mouse scroll when the user clicks the map
    $('.map').on('click', onMapClickHandler);
    </script>
