<div class="container-in">
    <header class="header-page">
        <h1 class="text-center">Recupere sua senha</h1>
    </header>
        <form method="POST" action="login/esqueciasenha" id="frmRecuperar" class="form-center">
                <div class="col-5 mg">
                    <label for="user">Informe seu login</label>
                    <input type="text" name="UsuarioLogin" id="user" class="form-control" value="" autocomplete=off required>
                    <span id="txtforgot" class="text-warning"></span>
                </div>
                <div class="col-lg-2 mg">
                    <button type="submit" name="button" class="btn btn-black">Recuperar</button>
                </div>
        </form>

    <div id="result" class="form-center mg clear">
        <span id="retorno"></span>
    </div>
</div>