
<?php // echo $view_redirect ?>

<section class="container-in">
    <div class="form-image text-center">
        <div style="padding: 0 25% 0 25%">
            <div style="border-radius: 20px">
                <a href="">
                    <img src="content/images/ejmeri-1.png"  style="width: 80%; margin: 0 auto;"class="img-responsive" alt="">                                                        
                </a>
            </div>
        </div>
        <h3>Patinha Fácil</h3>
        <span class="">Somos uma plataforma digital que buscamos auxiliar pessoas que desejam adotar ou doar um animalzinho.</span>            
        <br>
        <br>
        <div>  
            <div class="row"> 
                <span class="">São muitos pets disponíveis para adoção <i class="fa fa-heart" style="color:red;">  </i> <i class="fa fa-paw"></i> </span>
            </div>
        </div>
        <br>
        <?php if(count($view_lista) > 2) { ?>
        <section class="no-padding" id="portfolio">
            <div class="container-fluid">
                <div class="row no-gutter popup-gallery">
                    <?php foreach ($view_lista as $li => $a) { ?>
                    <div class="col-lg-4 no-padding col-sm-6">
                        <a href="uploads/<?php echo $a['Imagem']; ?>" class="portfolio-box">
                            <img src="uploads/<?php echo $a['Imagem']; ?>" class="img-responsive" alt="">
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    <div class="project-category text-faded">
                                        <?php echo $a['Nome']; ?>
                                    </div>
                                    <div class="project-name">
                                        <?php echo ' DDD('.$a['Ddd'].') <br> '. $a['Estado']. ''; ?>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </section>
        <?php  }
        else {
        ?>
        <section class="no-padding" id="portfolio">
            <div class="container-fluid">
                <strong>Em breve muitos pets estarão aqui</strong>
            </div>
        </section>
        <?php } ?>
    </div>
    <div class="container-right" id="frame">   
        <div class="form">
            <div class="form-insert">  
                <article class="option-people margem-cellphone">
                    <section class="login-cabecalho">
                        <h2 class="text-center">Crie uma conta gratuita e ajude um animalzinho! <i class="fa fa-heart" style="color:red"></i></h2>
                    </section>
                    <section class="login-cabecalho">
                        <h3 class="text-center">Forneça suas informações</h3>
                    </section>
                    <h5 class="">Tipo de pessoa</h5>
                    <div class="item-left margem-cellphone">
                        <a href="javascrip:;" id="linkfisica" class="btn btn-dark">Fisíca</a>  
                    </div>
                    <div class="item-right margem-cellphone">
                        <a href="javascrip:;" id="linkjuridica" class="btn btn-dark">Jurídica</a>                        
                    </div>
                </article>
            </div>
            <form id="frmCadastro" method="POST" action="login/index/<?php echo $view_redirect ?>" class="form-insert">
                <input type="hidden" name="Id" value="0">
                <div class="acess clear" style="padding-top:10px">
                    <h3>Informações Gerais</h3>
                </div>
                    <div class="item-left">
                        <label for="CPF" id="label"></label>
                        <input type="text" id="txtcpfcnpj" name="PessoaCpfCnpj" class="form-control"  value="" minlength=11 maxlength=14 autocomplete=off placeholder="CPF" required onkeyup="ValidateCPFCNPJ(this.value)">
                        <!--<input type="text" id="CNPJ" name="Cnpj" class="form-control cnpj" value="" autocomplete=off placeholder="00.000.000/0000-00" required onkeyup="ValidateCPFCNPJ(this.value)">-->
                        <span id="txtCPF" class="text-warning"></span>                                                        
                    </div>
                <!--<div class="item-right">
                    <label for="RG" id="number"></label>
                    <input type="text" name="PessoaRg" id="Rg" class="form-control" value="" placeholder="RG" required autocomplete=off>
                </div> -->
                <div class="item-right">
                    <label for="Nome" id="nome"></label>
                    <input type="text" name="PessoaNome" id="Nome" class="form-control" value="" placeholder="Nome" required maxlength=80 autocomplete=off>
                </div>
                <!--<div class="item-right">
                    <label for="Apelido" id="apelido"></label>
                    <input type="text" name="PessoaApelido" id="Apelido" class="form-control" value="" placeholder="Apelido" required autocomplete=off>
                </div>-->
                <!--<div class="item-left clear">
                    <label for="Email"></label>
                    <input type="email" name="EmailNome" id="Email" class="form-control" value=""placeholder="E-mail" autocomplete=off required placeholder="example@example.com">
                </div>
                <div class="item-right bottom">
                    <label for="tipoEmail"></label>
                    <select class="form-control" name="EmailTipoEmailId" required>
                        <option value="">Selecione o Tipo de E-mail</option>
                        <?php if (count($view_list) > 0) { ?>
                            <?php foreach ($view_list as $tipoemail) { ?>
                                <option value=<?php echo $tipoemail['Id']; ?>> <?php echo $tipoemail['Nome'];?></option><?php } } ?>
                    </select>
                </div>-->
                <div class="acess clear" style="padding-top:10px">
                    <h3>Informações de contato</h3>
                </div>
                <div class="item-left clear">
                    <label for="user"></label>
                    <input type="text" name="TelefoneNumero" id="Telefone" class="form-control cellphone" value="" placeholder="(DDD + Número)" autocomplete=off required>
                </div>
                <div class="item-right">
                    <label for="password"></label>
                     <select class="form-control" name="TelefoneTipoTelefoneId" required>
                        <option value="">Selecione o Tipo de Telefone</option>
                        <?php if (count($view_tipotelefone) > 0) { ?>
                            <?php foreach ($view_tipotelefone as $tipo) { ?>
                                <option value=<?php echo $tipo['Id']; ?>> <?php echo $tipo['Nome'];?></option><?php } } ?>
                    </select>
                </div>
                <div class="acess clear" style="padding-top:10px">
                    <h3>Informações de acesso</h3>
                </div>
                <div class="item-left clear">
                    <label for="user"></label>
                    <input type="email" name="UsuarioLogin" id="user" class="form-control" value="" placeholder="E-mail" minLength=3 maxLength=255 autocomplete=off required>
                    <span id="returnlogin" class="text-warning"></span>
                </div>
                <div class="item-left clear">
                    <label for="password"></label>
                    <input type="password" name="UsuarioSenha" id="password" class="form-control" placeholder="Senha" minlength=6 value="" required>
                </div>
                <div class="item-right">
                    <label for="repassword"></label>
                    <input type="password" id="repassword" name="repassword" class="form-control" value="" placeholder="Confirmar Senha" required>
                </div>
                <div class="item-left margem clear">
                    <button type="submit" id="Create" name="button" class="btn btn-blue">Cadastrar</button>
                </div>

                <div class="clear padding">
                    <h5>Ao se cadastrar, eu concordo com os <a href="ajuda/termos" target="_blank">Termos de uso</a> do Patinha Fácil, e também, em receber comunicações da Patinha Fácil, por exemplo, mensagens via e-mail de pessoas interessadas em adotar ou doar algum pet.</h5>                    
                </div>
                <!-- <div class="col-lg-10 clear padding">
                                       
                   <strong>Estou de acordo com os termos</strong> <input type="checkbox" class="checkbox" name="" required>
                </div> -->
            </form>
        </div>
        <div  style="display: none;" id="spin" class="text-center padding">
            <div class="loader">
            </div>
            <strong>Salvando suas informações...</strong>
        </div>
        <div id="result" class="form-insert">
            <span id="txtHint"></span>
        </div>

        
        <!-- <a href="https://www.facebook.com/dialog/oauth?client_id=YOUR_APP_ID&redirect_uri=YOUR_REDIRECT_URI&scope=COMMA_SEPARATED_LIST_OF_PERMISSION_NAMES">Entrar com Facebook</a> -->


        <!--<button type="button" onclick="loadshow();" id="btnspin"> Salvar</button>-->
    </div>                                          
</div>

</section>

<script>

function loadshow() {
    $('#spin').css("display", "block");
    
}
</script>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-102556198-1', 'auto');
  ga('send', 'pageview');

</script>