<div class="container-in">

    <form method="POST" action="pets/adotar" id="ConfirmarAdocao">
        <input type="hidden" name="AnimalId" value="<?php echo $view_pet['Id']; ?>">
        <header class="header-page">
		    <h1 class="text-center">Confirme sua adoção</h1>            
        </header>
			<div class="col-lg-10 animal" id="portfolio">
                <div class="no-gutter popup-gallery">
                    <a href="uploads/<?php echo $view_pet['Imagem']; ?>" class="portfolio-box">
                        <div id="photo-confirm"><img src="uploads/<?php echo $view_pet['Imagem']; ?>" class="foto" alt="Foto do animal"></div>
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Clique para ampliar
                                </div>
                            </div>
                        </div>
                    </a>
                    <span>Clique na imagem para ampliar</sxpan>                    
                </div>
			</div>
			<div class="info-confirmpet">
                <div class="info-pet">
                    <strong>Nome</strong><br>
                    <span><?php echo $view_pet['Nome']; ?></span>
                </div>
                <div class="info-pet">
                    <strong>Idade</strong><br>
                    <span><?php echo $view_pet['DtNascimento']; ?></span>
                </div>
                <div class="info-pet">
                    <strong>Pelagem</strong><br>
                    <span><?php echo $view_pet['Pelagem']; ?></span>
                </div>
			</div>

            <header class="header-page clear">
                <h1 class="text-center">Informações do atual responsável pelo PET</h1>
            </header>
			<div class="info-people clear">
				<strong>Nome</strong>
				<p><?php echo $view_pessoa['Nome']; ?><p>
            </div>
            <hr>
            <div class="info-people">
                <div class="col-lg-4">
                    <strong>Formas de contato</strong>
                    <hr>                  
                </div>
                <div class="col-lg-2 clear">
                    <strong>Telefones</strong> <br>
                    <?php if (count($view_telefones) > 0) { ?>
                                <?php foreach ($view_telefones as $telefone) { ?>
                                    <i <?php echo (strlen($telefone['Numero']) == 9 ? 'class="fa fa-whatsapp" aria-hidden="true"' : 'class="fa fa-phone" aria-hidden="true"'); ?>></i><span> <?php echo $telefone['Numero'];?></span><br>
                    <?php } } ?>
                    <!--<p>(00) 0000-0000</p>-->
                </div>
                <div class="col-lg-6">
                    <strong>E-mail</strong> <br>
                    <i class="fa fa-envelope-o fa-fw"></i><a  href="<?php echo ' mailto:'.$view_email['Login'];?>"><?php echo $view_email['Login'];?></a><br>
                    <!--<p>(00) 0000-0000</p>-->
                </div>
                <div class="clear col-lg-4">
                    <hr>
                </div>
            </div>
            <div class="info-people clear">
                <strong><i class="fa fa-map-marker" aria-hidden="true"></i> Localização</strong>
                <p><?php echo $view_endereco['Logradouro'].', '.$view_endereco['Numero'].' - '.$view_endereco['Bairro'].', '.$view_endereco['Cidade'].' - '.$view_endereco['UF'].' - '.$view_endereco['CEP']; ?></p>
            </div>
            <div class="info-people">
                <strong class="text-warning">Em caso de confirmação</strong>
                <p>Será enviado um e-mail para o responsável com suas Informações e caso o pet ainda esteja disponível, vocês entrarão em contato.</p>
            </div>
			<div id="botaoconfirmar">
                <input type="submit" name="save" id="botao" value="Quero adotar" class="btn btn-black btn-lg">
			</div>
    </form>
    <div id="result" class="mg clear">
        <span id="txtretorno">
            
        </span>
    </div>

</div>
