
<?php /*echo print_r($view_dados);*/ ?>

<section>
    <div class="container">
        <header class="header-page">
            <h1 class="text-center">Olá! Meu nome é <?php echo $view_dados['Nome'] ? $view_dados['Nome'] : "Sem nome"; ?>, veja mais sobbre mim</h1>
        </header>
        <article>
            <div class="photos">
                   <?php  echo '<img class="photo-pet" src="uploads/'.$view_dados['Imagem'].'" alt="Animal">'; ?>          
            </div>
            <div class="item-right">
                <div class="info-pet">
                    <strong>Pelagem</strong><br>
                    <span><?php echo $view_dados['Pelagem']; ?></span>
                </div>
                <div class="info-pet">
                    <strong>Raça</strong> <br>
                    <span><?php echo $view_dados['Raca']; ?></span>
                </div>
                <div class="info-pet">
                    <strong>Peso</strong><br>
                    <span><?php echo $view_dados['Peso'].' kgs'; ?></span>
                </div>
                <div class="info-pet">
                    <strong>Porte</strong><br>
                    <span><?php echo $view_dados['Porte']; ?></span>
                </div>
                <div class="info-pet">
                    <strong>Idade</strong> <br>
                    <span><?php echo $view_dados['DtNascimento']; ?></span>
                </div>
            </div>
            <!--<div class="photos">
                <div class="w3-content w3-display-container">
                        <img class="none photo-pet" src="content/images/humanpet.jpg" style="width:100%">
                        <img class="none photo-pet" src="content/images/landscape.jpg" style="width:100%">
                        <img class="none photo-pet" src="content/images/humanpet.jpg" style="width:100%">
                        <img class="none photo-pet" src="content/images/pet.jpg" style="width:100%">
                </div>-->
            
                <!--<div class="buttons clear">
                    <button style="float:left;" class="btn btn-dark" onclick="plusDivs(-1)">&#10094; Anterior</button>
                    <button style="float:right;" class="btn btn-dark" onclick="plusDivs(1)">Próxima &#10095;</button>
                </div>-->
            <!--</div>-->
<!--
            <div style="padding-top: 45px;">
               <form method="post" action="pets/confirmar" class="clear">
                    <input type="hidden" name="Id" value=<?php echo $view_dados['Id']; ?>>                                                                           
                    <button type="submit" name="button" class="btn btn-dark btn-font" title="Adote!">Quero adotar <i class="fa fa-heart"></i> </button> 
                </form>
            </div>-->
            <!--<section class="none" id="retorno">
                <h3>Para continuar efetue seu login</h3>
                <strong><a href="login" target="_blank">Clique aqui!</a></strong>
            </section>-->
            <section id="infopet" class="informations-pet">
                <header class="header-page">
                    <h3 class="text-center">Minha história e onde estou</h3> 
                </header>
                <div class="info-pet">
                    <strong>Uma breve descrição/história</strong>
                    <p><?php echo $view_dados['Descricao']; ?></p>
                </div>
                  <div class="clear">
                    <a href="pets/confirmar/<?php echo $view_dados['Id']; ?>" class="btn btn-black btn-font" title="Adote!">Quero adotar <i class="fa fa-heart"></i> </a> 
                </div>
            </section>                      
        </article>
    </div>
</section>

                                <!--CARROUSEL PET DETAILS -->                                    
<!--<script>
    var myIndex = 1;
    carousel();
    var slideIndex = 1;
    swapphoto(slideIndex);

    function plusDivs(n) {
        swapphoto(slideIndex += n);
    }

    function swapphoto(n) {
        var i;
        var x = document.getElementsByClassName("none");
        if (n > x.length) {slideIndex = 1}    
        if (n < 1) {slideIndex = x.length}
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";  
        }
        x[slideIndex-1].style.display = "block"; 
        
    }

    
function carousel() {
    var i;
    var x = document.getElementsByClassName("none");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 3000);
}
        
</script>-->
