<?php //echo print_r($view_animal); ?>



<div class="container-in" style="margin-bottom:5%;" ng-app="">
    <header class="header-page text-center">
        <h1 class="">Editar informações</h1>
        <h5>Escolha as novas informações do pet</h5>
    </header>

    <form method="POST" enctype="multipart/form-data" id="frmNovoPet" action="pets/editar" class="form-insert">
        <input type="hidden" name="AnimalId" value="<?php echo $view_animal['Id']; ?>">
        <div class="item-left clear">
            <label for="especie" id="">Espécie</label>
            <select class="form-control" id="especie" name="especie" onchange="showRaca(this.value);" required>
                <option value="">Selecione a Espécie</option>
                <?php if($view_especie > 0) { ?><?php foreach ($view_especie as $li => $a) { ?>
                <option value=<?php echo $a['Id']; ?> <?php echo ($a['Id'] == $view_animal['EspecieId'] ? 'selected' : ''); ?>> <?php echo $a['Nome']; ?></option><?php } } ?>
            </select>
        </div>
        <div class="item-right" id="raca">
            <label for="raca" id="">Raça</label>
            <select class="form-control" name="AnimalRacaId" required>
                <option value="">Selecione a Raça</option>
                <?php if($view_raca > 0) { ?><?php foreach ($view_raca as $li => $a) { ?>
                <option value=<?php echo $a['Id']; ?> <?php echo ($a['Id'] == $view_animal['RacaId'] ? 'selected' : ''); ?>> <?php echo $a['Nome']; ?></option><?php } } ?>
            </select>
        </div>
        <div class="item-left">
            <label for="Nome" id="">Nome</label>
            <input type="text" name="AnimalNome" id="nome" class="form-control"  value="<?php echo $view_animal['Nome']; ?>" maxlength=45 autocomplete=off placeholder="Caso não tenha, escreva: Sem Nome" required>
        </div>
        <div class="item-right">
            <label for="pelagem" id="">Pelagem</label>
            <select class="form-control" name="AnimalPelagemId" required>
                <option value="">Selecione a Pelagem</option><?php if($view_pelagem > 0) { ?><?php foreach ($view_pelagem as $li => $a) { ?>
                <option value=<?php echo $a['Id']; ?> <?php echo ($a['Id'] == $view_animal['PelagemId'] ? 'selected' : ''); ?>> <?php echo $a['Nome']; ?></option><?php } } ?>
            </select>
        </div>
        <div class="item-left clear">
            <label for="genero" id="teste">Genêro</label>
            <select class="form-control" name="AnimalGeneroId" required>
                <option value="">Selecione o Genêro</option><?php if($view_genero > 0) { ?><?php foreach ($view_genero as $li => $a) { ?>
                <option value=<?php echo $a['Id']; ?> <?php echo ($a['Id'] == $view_animal['GeneroId'] ? 'selected' : ''); ?>> <?php echo $a['Nome']; ?></option><?php } } ?>
            </select>
        </div>
        <div class="item-right">
            <label for="porte" id="">Porte</label>
            <select class="form-control" name="AnimalPorteId" required>
                <option value="">Selecione o Porte</option><?php if($view_porte > 0) { ?><?php foreach ($view_porte as $li => $a) { ?>
                <option value=<?php echo $a['Id']; ?> <?php echo ($a['Id'] == $view_animal['PorteId'] ? 'selected' : ''); ?>> <?php echo $a['Nome']; ?></option><?php } } ?>
            </select>
        </div>
        <div class="item-left clear">
            <label for="peso" id="">Peso</label>
            <input type="number" class="form-control" name="AnimalPeso" id="peso" value="<?php echo $view_animal['Peso']; ?>" required>
        </div>
        <div class="item-right">
            <label for="dtnascimento" id="">Idade</label>
            <input type="text" class="form-control" name="AnimalDtNascimento" id="dtnascimento"  value="<?php echo $view_animal['DtNascimento']; ?>" placeholder="Ex: Por volta de 1 ano">
        </div>
         <div class="item-left">
            <label for="area" id="">Animal castrado</label>
            <select class="form-control" name="AnimalCastrado" required>
                <option value="">Selecione</option>
                <option value="2"  <?php echo (1 == $view_animal['Castrado'] ? 'selected' : ''); ?>>Não</option>
                <option value="1"  <?php echo (2 == $view_animal['Castrado'] ? 'selected' : ''); ?>>Sim</option>
            </select>
        </div>
        <div class="item-right">
            <label for="area" id="">Área</label>
            <select class="form-control" name="AnimalAreaId" required>
                <option value="">Selecione o área</option><?php if($view_area > 0) { ?><?php foreach ($view_area as $li => $a) { ?>
                <option value=<?php echo $a['Id']; ?> <?php echo ($a['Id'] == $view_animal['AreaId'] ? 'selected' : ''); ?>> <?php echo $a['Nome']; ?></option><?php } } ?>
            </select>
        </div>
        <div class="item-right mg">
            <label for="genero" id="teste"><strong>Pet Encontrado/Adotado?</strong></label>
            <select class="form-control" name="AnimalAdotado" required>
                <option value="0" <?php echo ($view_animal['Adotado'] == '0' ? 'selected' : ''); ?>>Não</option>
                <option value="1" <?php echo ($view_animal['Adotado'] == '1' ? 'selected' : ''); ?>>Sim</option>
            </select>
        </div>
        <div class="clear">
            <label for="descricao" id="">Descreva um pouco sobre o pet e/ou algumas informações suas</label> <br>
            <textarea id="descricao" maxlength=500 name="AnimalDescricao" placeholder="" class="textarea" onkeyup="countChar(this, 'labelcount')" required><?php echo $view_animal['Descricao']; ?></textarea>
            <strong>Você ainda tem </strong><strong id="labelcount" class="text-warning">500</strong> <strong>caracteres para escrever.</strong>
        </div>
        <div class="clear">
            <!--<strong class="text-warning">Dica: </strong> <span>segure a tecla control (Ctrl) para selecionar múltiplas imagens.</span><br>            -->
            <strong>
                <i class="fa fa-image fa-5x" style="color: #57a3e8;"></i> Clique aqui para escolher a foto do pet (Sugestão de tamanho: 650x350px).
            </strong>
            <input type="file" name="image" id="file6" class="realupload form-control" accept="image/png, image/jpeg"/>
            <input type="hidden" name="ImagemId" value="<?php echo $view_imagem['Id']; ?>">
        </div>
        <div class="clear">
            <input type="submit" id="savepet" name="botao" value="Salvar" class="btn btn-black">                
        </div>
    </form>

    <div  style="display: none;" id="spin" class="text-center padding">
        <div class="loader">
        </div>
        <strong>Salvando informações...</strong>
    </div>

    <div id="result" class="form-insert clear" style="padding-top: 10px">
        <span id="txtretorno">
            
        </span>
    </div>

    <br>
    <br>
    <div class="form-insert objcenter">
        <h3>Pré-visualização</h3>
        <div class="image-holder mg" id="image-holder">
            <?php  echo '<img src="uploads/'.$view_imagem['Nome'].'" alt="Animal">'; ?>   
        </div>  
    </div>

   
</div>


<script  type="text/javascript">
   $("#file6").on('change', function () {

        if (typeof (FileReader) != "undefined") {

            var image_holder = $("#image-holder");
            image_holder.empty();

            var reader = new FileReader();
            reader.onload = function (e) {
                $("<img />", {
                    "src": e.target.result,
                    "class": "thumb-image"
                }).appendTo(image_holder);

            }
            image_holder.show();
            reader.readAsDataURL($(this)[0].files[0]);
        } else {
            alert("This browser does not support FileReader.");
        }
    });

     function showRaca(especie, table = '') {
            postPartialView('pets/ListaRaca/' + especie + '/' + table, 'raca');        
    }
</script>