<?php //print_r($view_pets); ?>

<div class="container-in" >
    <header class="header-page">
        <h1 class="text-center">Minhas Informações</h1>
    </header>

        <div class="tab" id="tabpessoa">
            <div class="tablinks">
                <a href="#retornoPessoa">Gerais</a>                
            </div>
            <div class="tablinks">
                <a href="javascript:;" class="tablinks">Acesso</a>                
            </div>
            <div class="tablinks">
                <a href="#tabdados" class="tablinks" >Dados para contato</a>    
            </div>
            <div class="tablinks">
                <a href="#tabendereco" class="tablinks">Endereço</a>                
            </div>
            <div class="tablinks">
                <a href="pessoa/pets" class="tablinks">Meus animais</a>                       
            </div>
            <div class="tablinks">
                <a href="#tabpreferencias" class="tablinks">Minhas preferências</a>   
            </div>
        </div>

        <div id="retornoPessoa">
            <h2>Informações Gerais</h2>
            <form method="POST" id="pessoa" class="tabcontent inline-table" action="pessoa">
                <input type="hidden" name="PessoaId" value="<?php echo $view_dados['Id']; ?>">
                <div class="col-8 inline-table padding col-fl">
                    <div class="item-left">
                        <strong>Nome/Razão Social</strong>
                        <input type="text" id="txtpeoplenome" name="PessoaNome" value="<?php echo $view_dados['Nome']; ?>" class="form-control" required>
                    </div>
                    <div class="item-right">
                        <strong>CPF/CNPJ</strong>
                        <input type="text" id="txtpeoplecpf" name="PessoaCpfCnpj" value="<?php echo $view_dados['CpfCnpj']; ?>" class="form-control" autocomplete=off placeholder="" required  onkeyup="ValidateCPFCNPJ(this.value)">
                        <span id="txtCPF" class="text-warning"></span>
                    </div>
                    <div class="item-left clear">
                        <strong>Apelido/Nome Fantasia</strong>
                        <input type="text" id="txtpeopleapelido" name="PessoaApelido" value="<?php echo $view_dados['Apelido']; ?>" placeholder="" class="form-control" required >
                    </div>
                    <div class="item-right">
                        <strong>RG/Inscrição Estadual</strong>
                        <input type="text" id="txtpeoplerg" name="PessoaRg" value="<?php echo $view_dados['Rg']; ?>" class="form-control" maxlength=45 required>
                    </div>
                </div>
                <div class="col-lg-5 clear">
                    <!--<button type="button" onclick="canceleditpeople('pessoa')" id="cancel" class="btn btn-black">Cancelar</button>
                    <button type="button" onclick="editpeople('pessoa')" id="edit" class="btn btn-black">Editar</button>
                    <button type="button" onclick="SubmitPartialForm($('#pessoa'), 'retornoPessoa')" id="save" name="save" class="btn btn-blue" data-toggle="modal" data-target="#myModal">Salvar</button>-->
                    <input type="submit" name="SavePeople" value="Salvar" class="btn btn-black">
                </div>
            </form>
        </div>
        <hr class="clear">
        <div id="retornoAcesso" style="margin-bottom:2%;">
            <h2>Informações de acesso</h2>
            <form method="POST" id="acesso" class="tabcontent" action="pessoa">
                <input type="hidden" name="UsuarioId" value="<?php echo $view_user['Id']; ?>">
                <div class="col-lg-10 padding">
                    <div class="item-left">
                        <strong>E-mail</strong>
                        <input type="text" id="fieldlogin" name="UsuarioLogin" value="<?php echo $view_user['Login']; ?>" class="form-control" required readonly>
                    </div>
                    <div class="item-right">
                        <strong>Senha</strong>
                        <div style="margin-top: 3%;">
                            <strong class="clear">***********</strong>                        
                        </div>
                    </div>
                </div>
                <div class="col-40 col-sm-1 col-fl clear" id="divedit" style="margin-bottom:2%;">
                    <div>
                        <strong>Senha antiga</strong>
                        <input type="password" id="" name="SenhaAntiga" onkeyup="ValidatePass(this.value)" value="" class="form-control" required autocomplete=off>
                        <span class="text-warning" id="oldpass"></span>
                    </div>
                    <div>
                        <strong>Nova Senha</strong>
                        <input type="password" id="password" name="UsuarioSenha"  onkeyup="validatepassword(repassword)" minlength=6 value="" class="form-control" required autocomplete=off>
                    </div>
                      <div>
                        <strong>Confirme a senha</strong>
                        <input type="password" id="repassword" onkeyup="validatepassword(this.value)" name="ConfirmarSenha" value="" class="form-control" required autocomplete=off>
                        <span class="text-warning" id="passretorno"></span>
                    </div>
                </div>
                <div class="col-lg-5 clear">
                    <button type="button" onclick="canceledititempeople('acesso', 'divedit')" id="cancel" class="btn btn-black">Cancelar</button>
                    <button type="button" onclick="savepeople('acesso', 'divedit')" id="new" class="btn btn-black">Editar</button>
                    <!--<button type="button" onclick="SubmitPartialFormAcesso($('#acesso'), 'retornoAcesso')" id="save" name="save" class="btn btn-blue" data-toggle="modal" data-target="#myModal">Salvar</button>-->
                    <input type="submit" name="SaveAcesso" id="save" value="Salvar" class="btn btn-black">
                </div>
            </form>
        </div>
        <hr class="clear">
        <div class="tabcontent" id="tabdados">
            <h2>Dados para contato</h2>
            <div id="retornoTelefone" class="clear">
                <div class="col-lg-10">
                    <div class="col-lg-5">
                        <strong>E-mail: </strong>
                        <input type="text" id="fieldlogin" name="UsuarioLogin" value="<?php echo $view_user['Login']; ?>" class="form-control" required readonly>
                    </div>
                </div>
                
                <!--<div class="col-lg-4 clear">
                    <strong>Lista de Telefones</strong>
                    <select class="form-control block" id="telefones" onchange="ChangeTelefone(this.value)">
                        <option value="0">Selecione o Telefone</option><?php if (count($view_telefones) > 0) { ?><?php foreach ($view_telefones as $telefone) { ?>
                        <option value=<?php echo $telefone['Id']; ?>><?php echo $telefone['Numero'];?></option><?php } } ?>
                    </select>                      
                </div> -->

                <form method="POST" id="telefone" class="col-lg-10" action="pessoa">
                    <input type="hidden" name="TelefoneId" id="Id" value="<?php echo $view_telefone['Id'] ?>">
                    <input type="hidden" name="teste" id="botao" value="">
                    <div class="col-lg-5" id="divedit" style="margin-bottom:2%;">
                        <!--<div>
                            <strong>DDDs</strong>
                            <select class="form-control block" id="ddds" name="TelefoneDddId" onchange="" required>
                                <option value="">Selecione o DDD</option><?php if(count($view_ddd) > 0) { ?><?php foreach($view_ddd as $ddd) { ?>
                                <option value=<?php echo $ddd['Id']; ?>><?php echo $ddd['Nome'];?></option><?php }} ?>
                            </select>
                        </div>-->
                        <div>
                            <strong>Telefone</strong>
                            <input type="text" id="txtpeoplenome" name="TelefoneNumero" value="<?php echo $view_telefone['Numero'] ?>" class="form-control cellphone" required autocomplete=off>
                        </div>
                        <div>
                            <strong>Tipo de telefone</strong>
                            <select class="form-control block" id="tipotelefones" name="TelefoneTipoTelefoneId" onchange="" required>
                                <option value="">Selecione o tipo</option><?php if (count($view_tipotelefone) > 0) { ?><?php foreach ($view_tipotelefone as $tipotelefone) { ?>
                                <option value=<?php echo $tipotelefone['Id']; ?> <?php echo ($tipotelefone['Id'] == $view_telefone['TipoTelefoneId'] ? 'selected' : ''); ?>> <?php echo $tipotelefone['Nome'];?></option><?php } } ?>
                            </select>
                        </div>
                    </div>
                    <div>
                        <!--<div class="col-40 col-fl clear">
                            <div class="col-fl col-3">
                                <button type="button" onclick="canceledititempeople('telefone', 'divedit')" id="cancel" class="btn btn-black">Cancelar</button>
                            </div>
                            <div class="col-fl">
                                <button type="button" onclick="SubmitPartialForm($('#telefone'), 'retornoTelefone')" id="save" name="save" class="btn btn-blue" data-toggle="modal" data-target="#myModal">Salvar</button>
                            </div>
                        </div>-->
                        <div class="col-lg-5 clear">
                            <!--<button type="button" onclick="savepeople('telefone', 'divedit')" id="new" class="btn btn-black">Novo</button>-->
                            <input type="submit" name="SaveDados" class="btn btn-black"  value="Salvar">
                        </div>
                    </div>
                </form>
            </div>
        </div> 
        <hr class="clear">

        <div class="tabcontent col-10 inline-table padding col-fl" id="tabendereco">
            <h2>Localização</h2>
            <div id="retornoEndereco" class="clear">
                <!--<div class="col-lg-4">
                    <strong>Lista de Endereços</strong>
                    <select class="form-control block" id="telefones" onchange="ChangeEndereco(this.value)">
                        <option value="0">Selecione o endereço</option><?php if (count($view_enderecos) > 0) { ?><?php foreach ($view_enderecos as $endereco) { ?>
                        <option value=<?php echo $endereco['Id']; ?> <?php echo ($endereco['Id'] == $view_endereco['Id'] ? 'selected' : ''); ?>><?php echo $endereco['Nome'] ?></option><?php } } ?>
                    </select>                      
                </div>-->

                <form method="POST" id="endereco" class="" action="pessoa">
                    <input type="hidden" name="EnderecoId" id="Id" value="<?php echo $view_endereco['Id']; ?>">
                    <input type="hidden" name="teste" id="botao" value="">
                    <div id="diveditar">
                        <div class="clear col-lg-5">
                            <strong>Dê um apelido ao seu endereço</strong>
                            <input type="text" id="txtpeoplenome" name="EnderecoNome" value="<?php echo $view_endereco['Nome']; ?>" class="form-control" required autocomplete=off maxlength=45 placeholder="Exemplo: Casa da vovó">
                        </div>
                        <div class="clear">
                            <strong>CEP</strong>                            
                        </div>
                        <div class="form-inline">
                            <div class="form-group">
                                <input type="text" id="EnderecoCep" name="EnderecoCep" value="<?php echo $view_endereco['Cep']; ?>" class="form-control cep" required autocomplete=off maxnlength=8>
                            </div>
                            <div>
                                <span id="infocep" style="color:red;"></span>
                            </div>
                        </div>
                        <div class="clear col-lg-9">
                                <strong>Endereço</strong>
                                <input type="text" id="EnderecoLogradouro" name="EnderecoLogradouro" value="<?php echo $view_endereco['Logradouro']; ?>" class="form-control" required autocomplete=off maxlength=80>
                            </div>
                        <div id="carregaCep">
                            <div class="clear col-lg-9">
                                <strong>Bairro</strong>
                                <input type="text" id="EnderecoBairro" name="bairro" readonly class="form-control" required autocomplete=off maxlength=80>
                            </div>
                            <div class="clear col-lg-9">
                                <strong>Cidade</strong>
                                <input type="text" readonly id="EnderecoCidade" name="cidade" class="form-control" required autocomplete=off maxlength=80>
                            </div>
                        </div>
                        <div class="clear col-lg-4">
                            <div class="col-lg-10">
                                <strong>Número</strong>
                                <input type="number" id="txtpeoplenome" name="EnderecoNumero" value="<?php echo $view_endereco['Numero']; ?>" class="form-control" required autocomplete=off>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="col-lg-10">
                                <strong>Complemento</strong>
                                <input type="text" id="txtpeoplenome" name="EnderecoComplemento" value="<?php echo $view_endereco['Complemento']; ?>" class="form-control" autocomplete=off maxlength=45>
                            </div>
                        </div>
                        <div class="clear col-lg-9">
                            <strong>Ponto de referência</strong>
                            <input type="text" name="EnderecoPontoReferencia" value="<?php echo $view_endereco['PontoReferencia']; ?>" class="form-control" autocomplete=off maxlength=45>
                        </div>
                        <div class="col-lg-9">
                            <strong>Estado</strong>
                            <select class="form-control selectpicker" id="SelectEstados" data-live-search="true" onchange="CarregaDDD(this.value)" required>
                                    <!--<option value="">Selecione o estado</option>      -->
                                    <?php if($view_estados > 0) { ?>
                                        <?php foreach ($view_estados as $li => $a) { ?>
                                            <option data-tokens="<?php echo $a['Nome']; ?>" value=<?php echo $a['Sigla']; ?> <?php echo ($a['Id'] ==  $view_endereco['EstadoId'] ? 'selected' : ''); ?>> <?php echo $a['Nome']; ?></option>
                                    <?php 
                                        }
                                    } ?> 
                            </select>   
                        </div>
                        <div class="clear col-lg-9">
                            <strong>DDD + Região</strong>
                            <div id="RetornoDDD">
                                <select class="form-control" id="SelectDDD" name="EnderecoDddId" required>
                                        <?php if($view_ddd > 0) { ?>
                                        <?php foreach ($view_ddd as $li => $a) { ?>
                                            <option value=<?php echo $a['Id']; ?>  <?php echo ($a['Id'] ==  $view_endereco['DddId'] ? 'selected' : ''); ?> ><?php echo 'DDD - '.$a['Numero']. ' e Região: '.$a['Regiao'] ?>
                                    </option>
                                    <?php } } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="clear col-lg-10" style="padding-top:10px">
                        <!--<div class="col-lg-2">
                            <button type="button" onclick="saveend('endereco', 'divedit')" id="new" class="btn btn-black">Novo</button>
                        </div>
                        <div class="col-lg-2">
                            <button type="button" onclick="canceleditend('endereco', 'divedit')" id="cancel" class="btn btn-black">Cancelar</button>
                        </div>-->
                        <div class="col-lg-2">
                            <!--<input type="button" onclick="SubmitPartialForm($('#endereco'), 'retornoEndereco', 'MensagemEndereco')" id="save" name="save" value="Salvar" class="btn btn-blue">-->
                            <!--<button type="button" onclick="SubmitPartialForm($('#endereco'), 'retornoEndereco')" id="saveend" name="save" class="btn btn-blue" data-toggle="modal" data-target="#myModal">Salvar</button>-->
                            <input type="submit" name="SaveEndereco" value="Salvar" class="btn btn-black">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <hr class="clear">
        
        <div class="tabcontent col-10 inline-table col-fl extreme-padding" id="tabpreferencias">
            <h5>Forneça algumas preferências para nós, ela nos ajudará a filtrar animais para você. <span style="color:red">Não obrigatório.</span> </h5>
            <div id="retornoPreferencias" class="clear">
                <div class="item-left">
                    <strong>Espécie</strong>
                    <select class="form-control">
                        <option value="">Selecione a espécie</option>
                    </select>
                </div>
                <div class="item-right">
                    <strong>Raça</strong>
                    <select class="form-control" name="PreferenciaRacaId">
                        <option value="">Selecione a raça</option>
                    </select>
                </div>
                <div class="item-left">
                    <strong>Genêro</strong>
                    <select class="form-control" name="PreferenciaGeneroId">
                        <option value="">Selecione a genêro</option>
                    </select>
                </div>
                <div class="item-right">
                    <strong>Porte</strong>
                    <select class="form-control" name="PreferenciaPorteId">
                        <option value="">Selecione a porte</option>
                    </select>
                </div>
                <div class="item-left">
                    <strong>Pelagem</strong>
                    <select class="form-control" name="PreferenciaPelagemId">
                        <option value="">Selecione a pelagem</option>
                    </select>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><i class="fa fa-times-circle-o" aria-hidden="true"></i></button>
                    <h4 class="modal-title"><i class="fa fa-info" aria-hidden="true"></i> Atualizações.</h4>
                </div>
                <div class="modal-body">
                    <p>Os seus dados foram atualizados.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
</div>