
      <?php if (count($view_list) > 0) { ?>
                <?php foreach ($view_list as $li => $a){ ?>
                    <div class="grid-pet">
                        <div class="img-pet">
                            <?php  echo '<img src="uploads/'.$a['imagem'].'" alt="Animal">'; ?>                                
                        </div>
                        <div class="information-pet">
                            <div class="row">
                                <strong>Nome: </strong> <span><?php echo $a['nome']; ?></span>                                
                            </div>
                            <div class="row">
                                <strong>Raça: </strong> <span><?php echo $a['raca']; ?></span>                                
                            </div>
                            <div class="row">
                                <strong>Peso: </strong> <span><?php echo $a['peso'].'Kgs'; ?></span>                                
                            </div>
                            <div class="row">
                                 <strong>Idade: </strong> <span><?php echo $a['dtnascimento']; ?></span>                                 
                            </div>
                        </div>
                        <div class="adopt-pet">
                            <div class="information">
                                <!--<input type="submit" formaction="pets/petdetails" name="adotar" class="btn fa fa-5x" title="Adote!" value ="&#xf004;">                          -->
                                <!--<input type="button" name="information" value="Mais informações" class="btn button">                                  -->
                                <a href="pets/editar/<?php echo $a['id'] .'/'. hash('md5',$a['id']);?>" title="Editar <?php echo $a['nome']; ?>"><i class="fa fa-edit fa-5x" aria-hidden="true"></i></a>
                            </div>
                            <!--<div class="interest">
                                <a href="#" title="Demonstrar interesse!"><i class="fa fa-envelope-o fa-5x" aria-hidden="true"></i></a>                                
                            </div>-->
                        </div>
                    </div>                
        <?php 
                }
        }
else { ?>
            <div>
                <div class="alert alert-info alert-dismissable text-center" style="background-color: rgba(200,200,200,0.2); border-radius: 40px">
                        <h1 style="color:black">Você não tem animais com esses filtros.</h1> 
                        <!--<h3><a href="login/index/pets/adotar/'.$obj->Id.'" class="btn btn-purple btn-lg">Clique aqui</a> </h3>-->
                </div>
            </div>
        <?php }
        
        ?>
