<section id="list-animal" class="">
    <div class="container-in">
        <header class="about text-center">
            <h2>Pesquise o pet que você deseja oferecer</h2>
        </header>
    </div>
    <div class="grid-filter">    
        <div class="header-grid-filter">
            <a href="javascript:;" class="header-grid-text" id="filters">Filtros <i class="fa fa-angle-down fa-1x" aria-hidden="true"></i></a>
            <hr style="border: 1px solid #53a3e8">
        </div>
        <div class="items-filter padding" id="items-filter">
            <form method="POST" id="SearchPet" class="form-search"  action="pets/ListaPet">   
                <div class="filter col-sm-1">
                    <label for="especie"><strong>Espécie</strong></label>
                    <select class="form-control block" id="especie" name="FilterPetEspecieId" onchange="showFilterRaca(this.value);"> 
                        <option value="0">Selecione a espécie</option>      
                        <?php if($view_especie > 0) { ?>
                                <?php foreach ($view_especie as $li => $a) { ?>
                            <option value=<?php echo $a['Id']; ?>> <?php echo $a['Nome']; ?></option>
                        <?php 
                            }
                        } ?> 
                    </select>
                </div>
                <div class="filter" id="raca">
                <label for="raca"><strong>Raça</strong></label>
                    <select class="form-control block" id="raca" name="FilterPetRacaId">
                        <option value="0">Selecione uma espécie</option>
                    </select>
                </div>
                <div class="filter">
                    <label for="genero"><strong>Gênero</strong></label>
                    <select class="form-control block" id="genero" name="FilterPetGeneroId">
                        <option value="0">Selecione o gênero</option>      
                        <?php if($view_genero > 0) { ?>
                                <?php foreach ($view_genero as $li => $a) { ?>
                            <option value=<?php echo $a['Id']; ?>> <?php echo $a['Nome']; ?></option>
                        <?php 
                            }
                        } ?>  
                    </select>
                </div>
                <div class="filter">
                    <label for="cor"><strong>Pelagem</strong></label>
                    <select class="form-control block" id="pelagem" name="FilterPetPelagemId">
                        <option value="0">Selecione a pelagem</option>     
                        <?php if($view_pelagem > 0) { ?>
                                <?php foreach ($view_pelagem as $li => $a) { ?>
                            <option value=<?php echo $a['Id']; ?>> <?php echo $a['Nome']; ?></option>
                        <?php 
                            }
                        } ?>  
                    </select>
                </div>
                <div class="filter">
                    <label for="porte"><strong>Porte</strong></label>
                    <select class="form-control block" id="porte" name="FilterPetPorteId">
                        <option value="0">Selecione a o porte</option>      
                        <?php if($view_porte > 0) { ?>
                                <?php foreach ($view_porte as $li => $a) { ?>
                            <option value=<?php echo $a['Id']; ?>> <?php echo $a['Nome']; ?></option>
                        <?php 
                            }
                        } ?> 
                    </select>
                </div>
                <div>
                    <label for="" style="color:white">any</label> <br>
                    <button type="button" onclick="ListaAdotaveis('home/ListaAdotaveis/0', 'SearchPet', 'ListPeople')" class="btn btn-black"> <i class="fa fa-search"></i> PESQUISAR </button>                    
                </div>
                <div class="col-lg-12">
                    <hr style="border: 1px solid #53a3e8">
                </div>
            </form>
        </div>
    </div>
    <div class="clear container-in">        
        <div class="bs-docs-example">    
            <div class="result-search" id="ListPeople">       
                <!--    LISTA FEITA COM BASE EM PARTIALVIEW    -->
            
            </div>            
        </div>
    </div>
</section>


<script>
    
    $(document).ready(function(){
        showPeople();
    });
    function showFilterRaca(especie)
    {
        postPartialView('pets/FilterListaRaca/' + especie, 'raca');        
    }


</script>