<div class="container-in">
    <header class="about text-center">
        <h2>Termos e Condições Gerais de Uso</h2>
    </header>
    <hr style="max-width: 200px; border: 1px solid #53a3e8">
    <section id="start" class="form-insert padding">
        
            <h4> Seja bem-vindo! Antes de utilizar o Patinha Fácil, por favor, leia atentamente os presentes Termos e Condições Gerais de Uso. A leitura integral do presente documento é importante para a sua proteção, para a proteção do Patinha Fácil, além de garantir o nosso bom atendimento a Você. </h4>
            <p>1. Estes Termos e Condições são um contrato aceito por Você no momento em que Você faz uso do Patinha Fácil. Você deve estar ciente de que algumas das ferramentas oferecidas pelo Patinha Fácil estão sujeitas a condições particulares que regem o relacionamento dos envolvidos. </p>
            <p>2. No uso de nossas ferramentas, Você deve obedecer à legislação vigente, a moral, a ordem pública e estes Termos e Condições e demais condições particulares a cada caso, não podendo praticar nenhuma conduta, incluindo a publicação de animais, que sejam contrários a eles.</p>
            <p>3. Você deverá respeitar os direitos de propriedade intelectual do Patinha Fácil e autoriza a empresa a usar, para fins de publicidade, quaisquer fotografias, imagens e demais conteúdos fornecidos por Você e inseridos no website do Patinha Fácil. </p>
            <p>4. O Patinha Fácil não se responsabiliza por danos decorrentes dos negócios conduzidos por terceiros, Usuários ou não, pois sua atuação se limita a disponibilizar o espaço para adoção de animais e serviços diretamente pelos Usuários anunciantes. Por esse mesmo motivo, a Patinha Fácil não se responsabiliza pela conduta dos Usuários, por animais e serviços anunciados ou insucesso das negociações. </p>
            <p>5. Você é integralmente responsável por todos os atos praticados por Você. Da mesma forma, Você também é responsável pela veracidade das informações fornecidas, seja para o registro da conta, ou para a condução de suas negociações. </p>
            <p>6. O Patinha Fácil se reserva o direito de recusar, bloquear, inabilitar ou excluir, a seu exclusivo critério, Usuários que descumpram qualquer uma das disposições presentes nestes Termos e Condições.</p>
    </section>
</div>