    
    <section id="services" class="services">
		<div class="container-in">
				<div class="col-10 text-center">
					<h1>O que procura ?</h1>
					<hr class="small"/>
						<form method="POST" name="Services" action="pets">
							<div class="service-item col-fl col-tb-2 col-sm-1">
								<div class="">
									<span class="fa-stack fa-4x">
										<strong>Cães</strong>
										<!--<i class="fa fa-circle fa-stack-2x"></i>                                -->
										<!--<img src="content/images/Dog.ico" alt="icon-dog" style="width: 100%; height: 100%; border-radius: 10%;" />-->
										<!--<i class="fa fa-circle fa-stack-2x"></i>-->
										<!--<i class="fa fa-compass fa-stack-1x text-primary"></i>-->
									</span>
									<h4>
										<strong>São muitos cãezinhos</strong>
									</h4>
									<p><strong>Encontre aqui seu cãozinho.</strong></p>
									<input type="submit" name="Cão" class="btn btn-light" value="Veja mais">
								</div>
							</div>
							<div class="service-item col-fl col-tb-2 col-sm-1">
								<div class="">
									<span class="fa-stack fa-4x">
										<!--<img src="content/images/Cat-icon.png" alt="icon-cat" style="width: 100%; height: 100%; border-radius: 10%;" />-->
										<!--<i class="fa fa-circle fa-stack-2x"></i>-->
										<!--<i class="fa fa-cloud fa-stack-1x text-primary"></i>-->
										<strong>Gatos</strong>
									</span>
									<h4>
										<strong>São muitos gatinhos.</strong>
									</h4>
									<p><strong>Encontre aqui seu gatinho.</strong></p>
									<input type="submit" name="Gato" class="btn btn-light" value="Veja mais">
								</div>
							</div>
							<div class="service-item col-fl col-tb-2 col-sm-1">
								<div class="">
									<span class="fa-stack fa-4x">
										<!--<i class="fa fa-circle fa-stack-2x"></i> -->
										<i class="fa fa-question fa-stack-1x"></i>
										<!--<img src="content/images/adopt.png" alt="icon-adopt" style="width: 100%; height: 100%; border-radius: 10%;" />-->
										<!--<i class="fa fa-flask fa-stack-1x text-primary"></i>-->
									</span>
									<h4>
										<strong>Ajude-me</strong>
									</h4>
									<p><strong>Para quem doar ?</strong></p>
									<a href="#" class="btn btn-light">Veja a lista</a>
								</div>
							</div>
						</form>
				</div>
				<!-- /.col-lg-10 -->
		</div>
		<!-- /.container -->
	</section>

	<!-- Portfolio -->
	<section class="no-padding" id="portfolio" style="margin-bottom:5%; padding: 0;">
	    <div class="">
            <div class="">
                <div class="col-10 text-center">
                    <h2 class="section-heading">Alguns pets disponíveis para adoção <i class="fa fa-paw fa-1x"></i> </h2>
                    <hr class="small">
                </div>
            </div>
        </div>
        <div class="col-10 inline-table">
            <div class="no-gutter popup-gallery">
                <div class="col-lg-4 col-sm-6">
                    <a href="content/images/1.jpg" class="portfolio-box">
                        <img src="content/images/1.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                 <div class="project-category text-faded">
                                    Possível nome do PET
                                </div>
                                <div class="project-name">
                                    Algumas informações
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="content/images/2.jpg" class="portfolio-box">
                        <img src="content/images/2.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="content/images/3.jpg" class="portfolio-box">
                        <img src="content/images/3.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Possível nome do PET
                                </div>
                                <div class="project-name">
                                    Algumas informações
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="content/images/4.jpg" class="portfolio-box">
                        <img src="content/images/4.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="content/images/5.jpg" class="portfolio-box">
                        <img src="content/images/5.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="content/images/6.jpg" class="portfolio-box">
                        <img src="content/images/6.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
