	<section id="services" class="services">
		<div class="container">
				<div class="col-10 text-center">
					<h1>O que procura ?</h1>
					<hr class="small"/>
						<form method="POST" name="Services" action="pets">
							<div class="service-item col-fl col-tb-2 col-sm-1">
								<div class="">
									<span class="fa-stack fa-4x">
										<strong>Cães</strong>
										<!--<i class="fa fa-circle fa-stack-2x"></i>                                -->
										<!--<img src="content/images/Dog.ico" alt="icon-dog" style="width: 100%; height: 100%; border-radius: 10%;" />-->
										<!--<i class="fa fa-circle fa-stack-2x"></i>-->
										<!--<i class="fa fa-compass fa-stack-1x text-primary"></i>-->
									</span>
									<h4>
										<strong>São muitos cãezinhos</strong>
									</h4>
									<p><strong>Encontre aqui seu cãozinho.</strong></p>
									<input type="submit" name="Cão" class="btn btn-light" value="Veja mais">
								</div>
							</div>
							<div class="service-item col-fl col-tb-2 col-sm-1">
								<div class="">
									<span class="fa-stack fa-4x">
										<!--<img src="content/images/Cat-icon.png" alt="icon-cat" style="width: 100%; height: 100%; border-radius: 10%;" />-->
										<!--<i class="fa fa-circle fa-stack-2x"></i>-->
										<!--<i class="fa fa-cloud fa-stack-1x text-primary"></i>-->
										<strong>Gatos</strong>
									</span>
									<h4>
										<strong>São muitos gatinhos.</strong>
									</h4>
									<p><strong>Encontre aqui seu gatinho.</strong></p>
									<input type="submit" name="Gato" class="btn btn-light" value="Veja mais">
								</div>
							</div>
							<div class="service-item col-fl col-tb-2 col-sm-1">
								<div class="">
									<span class="fa-stack fa-4x">
										<!--<i class="fa fa-circle fa-stack-2x"></i> -->
										<i class="fa fa-question fa-stack-1x"></i>
										<!--<img src="content/images/adopt.png" alt="icon-adopt" style="width: 100%; height: 100%; border-radius: 10%;" />-->
										<!--<i class="fa fa-flask fa-stack-1x text-primary"></i>-->
									</span>
									<h4>
										<strong>Ajude-me</strong>
									</h4>
									<p><strong>Para quem doar ?</strong></p>
									<a href="#" class="btn btn-light">Veja a lista</a>
								</div>
							</div>
						</form>
				</div>
				<!-- /.col-lg-10 -->
		</div>
		<!-- /.container -->
	</section>

	<!-- Portfolio -->
	<section id="portfolio" class="portfolio">
		<div class="container">
			<div class="row">
				<div class="col-90 text-center">
					<h2>Alguns pets disponíveis para adoção</h2>
					<hr class="small" />
					<div class="row">
						<div class="col-4 col-fl col-sm-1 col-tb-2">
							<div class="portfolio-item">
								<a href="#">
									<img class="img-animals" src="content/images/humanpet.jpg" />
								</a>
							</div>
						</div>
						<div class="col-4 col-fl col-sm-1 col-tb-2">
							<div class="portfolio-item">
								<a href="#">
									<img class="img-animals" src="content/images/pet.jpg" />
								</a>
							</div>
						</div>
						<div class="col-4 col-fl col-sm-1 col-tb-2">
							<div class="portfolio-item">
								<a href="#">
									<img class="img-animals" src="content/images/humanpet.jpg" />
								</a>
							</div>
						</div>
						<div class="col-4 col-fl col-sm-1 col-tb-2">
							<div class="portfolio-item">
								<a href="#">
									<img class="img-animals" src="content/images/pet.jpg" />
								</a>
							</div>
						</div>
					</div>
					<!-- /.row (nested) -->
					<a href="site/pets" class="btn btn-dark btn-lg">Veja mais animaizinhos</a>
				</div>
				<!-- /.col-lg-10 -->
			</div>
			<!-- /.row -->
		</div>
		<!-- /.container -->
	</section>
