<section id="start"> 
        <!-- About -->
    <section id="free" class="about">
        <div class="container-in">
            <div class="text-center">
                <h2>Aqui está o seu amigo!</h2>
                <p class="lead">Patinha Fácil.</p>
				<?php 
					if($view_auth['Autenticado'] == 0 )
						{
					?>		<p class="lead text-warning">Mandamos um E-mail para você confirmar sua conta, isso é importante para o seu próximo acesso.</p>
				<?php	} ?>
                <p class="lead">É a sua primeira vez por aqui ? Visite seu  <a href="pessoa"> Perfil <i class="fa fa-user-circle"></i></a></p>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>
    <section id="services" class="services">
		<div class="container-in">
				<div class="col-10 text-center">
					<h1>O que procura ?</h1>
					<hr class="small"/>
						<form method="POST" name="Services" action="pets">
							<div class="service-item col-fl col-tb-2 col-sm-1">
								<div class="">
									<span class="fa-stack fa-4x">
										<strong>Cães</strong>
										<!--<i class="fa fa-circle fa-stack-2x"></i>                                -->
										<!--<img src="content/images/Dog.ico" alt="icon-dog" style="width: 100%; height: 100%; border-radius: 10%;" />-->
										<!--<i class="fa fa-circle fa-stack-2x"></i>-->
										<!--<i class="fa fa-compass fa-stack-1x text-primary"></i>-->
									</span>
									<h4>
										<strong>São muitos cãezinhos</strong>
									</h4>
									<p><strong>Encontre aqui seu cãozinho.</strong></p>
									<!-- <input type="submit" name="Cão" class="btn btn-light" value="Veja mais"> -->
								</div>
							</div>
							<div class="service-item col-fl col-tb-2 col-sm-1">
								<div class="">
									<span class="fa-stack fa-4x">
										<!--<img src="content/images/Cat-icon.png" alt="icon-cat" style="width: 100%; height: 100%; border-radius: 10%;" />-->
										<!--<i class="fa fa-circle fa-stack-2x"></i>-->
										<!--<i class="fa fa-cloud fa-stack-1x text-primary"></i>-->
										<strong>Gatos</strong>
									</span>
									<h4>
										<strong>São muitos gatinhos.</strong>
									</h4>
									<p><strong>Encontre aqui seu gatinho.</strong></p>
								</div>
							</div>
							<div class="service-item col-fl col-tb-2 col-sm-1">
								<div class="">
									<span class="fa-stack fa-4x">
										<!--<i class="fa fa-circle fa-stack-2x"></i> -->
										<i class="fa fa-question fa-stack-1x"></i>
										<!--<img src="content/images/adopt.png" alt="icon-adopt" style="width: 100%; height: 100%; border-radius: 10%;" />-->
										<!--<i class="fa fa-flask fa-stack-1x text-primary"></i>-->
									</span>
									<h4>
										<strong>Ajude-me</strong>
									</h4>
									<p><strong>Para quem doar ?</strong></p>
									<a href="ajuda/pets" class="btn btn-light">Veja a lista</a>
								</div>
							</div>
						</form>
				</div>
				<!-- /.col-lg-10 -->
		</div>
		<!-- /.container -->
	</section>

	<!-- Portfolio -->
	<section class="no-padding" id="portfolio" style="padding: 0;">
        <?php if(count($view_lista) > 2) { ?>  
             <div class="">
                <div class="">
                    <div class="col-10 text-center">
                        <h2 class="section-heading">Alguns pets disponíveis para adoção <i class="fa fa-paw fa-1x"></i> </h2>
                        <hr class="small">
                    </div>
                </div>
            </div>
            <div class="col-10 inline-table">
                <div class="no-gutter">
            <?php foreach ($view_lista as $li => $a) { ?>
                    <div class="col-lg-4 col-sm-6">
                        <a href="pets/adotar/<?php echo $a['Id'] .'/'. hash('md5',$a['Id']) ?>" class="portfolio-box">
                            <img src="uploads/<?php echo $a['Imagem']; ?>" class="img-responsive img-450-250" alt="">
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    <div class="project-category text-faded">
                                        <?php echo $a['Nome']; ?>
                                    </div>
                                    <div class="project-name">
                                        <?php echo 'DDD ('.$a['Ddd'].') - '. $a['Estado']; ?>
                                    </div>
                                </div>
                            </div>
						</a>
                    </div>					
        <?php 
            } ?>
                </div>
            </div>
       <?php }
        else
        { ?>
            <div class="">
                <div class="">
                    <div class="col-10 text-center">
                        <h2 class="section-heading">Em breve muitos pets disponíveis para adoção <i class="fa fa-paw fa-1x"></i> </h2>
                        <hr class="small">
                    </div>
                </div>
            </div>
<?php   } ?> 
    </section>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-102556198-1', 'auto');
  ga('send', 'pageview');

</script>